### ISSUE TITLE
Mog'dorg the Wizened

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#102]
After turning in the quest, by his name, the next quests he is supposed to offer are not being offered by him

Dev Reply:there are 2 quests called "Mog'dord the Wizened" one is taken in shattrath after completing some other quests and another taken directly in Blade's Edge mountains. i am temporary removing previous quest condition. in next DB update. 

Reporter reply : I did both And these aren't being offered. 

I dont know about this quest but perhaps worth taking a look.

**Comment by Alucard-entropius** [comment]
quest ID **10989** doesnt give new quests
quest ID **10983** does give new quests, such as "Grulloc has two skulls", Maggoc's treasure chest" and Even Gronn has standards"
