### ISSUE TITLE
Shadowfiend not attacking

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#109]
This has happened to me a few times in BT and SWP and I watched it happen again today in BT to a priest on Bloodboil.  The shadowfiend is dropped and it just sits there not attacking and there is no mana return.  The shadowfiend has worked on other bosses.  I don't know what the pattern of the failure is.

 

This video is from Nov 28.  Jump to 2:15 if it doesn't start there. 

https://www.youtube.com/watch?v=C1sR9CKJKLk&feature=youtu.be

**Comment by Alucard-entropius** [comment]
Tested on both mentioned Bosses, many times, works just fine.
