### ISSUE TITLE
Stealth CD with Camouflage

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#113]
In regards to the Server Update - Revision 126,  there appears to be a new bug introduced with the patch note, "Fixed an issue that caused the client to incorrectly show no stealth cooldown when the player would log in while stealthed, and then left stealth"

 

With the Camouflage talent, coming out of stealth now is 10 seconds instead of 5 with that talent. 

Azelen: Only affects first cooldown after relog (if you logged off while stealthed).

**Comment by Nextcalibur** [comment]
Only affects first cooldown after relog (if you logged off while stealthed).
