### ISSUE TITLE
Kidney Duration bug

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#114]
Somehow, sometimes a 5 combo point kidney lasts only 3 seconds. There is no way it should be DRed since it's the first kidney of the game. Seems like it only happened on other rogues, as shown 3 times in the video below.  

https://www.youtube.com/watch?v=4pthnD52qdk&feature=youtu.be

     
    On 12/3/2018 at 7:39 PM, Azelen said:

    I was not able to replicate it on my local server, can you please post macros you've used in this video, please. Also have you seen this happening againt other classes, or does it happen only against rogues?

 

Kidney #1: premed macro
Kidney #2: premed macro
Kidney #3: premed macro and shadowstep kidney macro

 

Premeditation macro: 

#showtooltip premeditation

/equipslot 17 Brutal Gladiator's Shiv

/cast premeditation

 

Shadowstep kidney macro:

/cast shadowstep
/cast kidney shot

 

That's all.

 

I only remember having the bug 3 times and yes it was all against rogues. I tried to recreate it on priest and druid targets since I didn't have any rogue to duel. I was using the same macros though.

 

The equipslot 17 shouldn't do anything since I already had that dagger equipped, so I doubt it's the macro anyway.

 

Also, I checked my recordings and didn't find any other kidney bug vs the same teams using the same macros and stuff. On the same session.

 

Another thing in common in all the 3 clips is that the enemy rogue has used his own kidney a few seconds ago.. but I doubt that is causing the dr bug because it would be more common... or?

 

What a mystery ¯\_(ツ)_/¯

**Comment by Nextcalibur** [comment]
not enough info.
