### ISSUE TITLE
Fear Breaking from 1 hit

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#116]
Fear is soposed to fear the mob and there is a chance that dmg wil break the fear.

 

The problem is that fear breaks everytime on the first dmg tic.

 

this means that fear is rather usless, since you cant have a mob runing around feared and fully dottet up.

 

you dot up fear and then it is back on you hitting you, fear can atm only be used on a mob that is not taking dmg and that is wrong !

**Comment by Alucard-entropius** [comment]
Tested, DOT has a CHANCE to break the fear, but its deff that its not happening from first DOT. Moar DOTz increase the chance of one of them breaking fear. it also scales with amount of dmg.
