### ISSUE TITLE
Charge on Blade's

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#119]
Charge abilities on Blade's Edge Arena are taking super long paths

 

https://clips.twitch.tv/ObservantRelievedNightingaleSoBayed

 

It's even longer if you jump from the stone pillars as the charge will go across the bridge, down the ramp to it's target :D

 

One year ago when I was playing here it wasn't like this. 
https://clips.twitch.tv/ObservantRelievedNightingaleSoBayed

**Comment by Nextcalibur** [comment]
Working as intended.
