### ISSUE TITLE
Counterattack!

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#12]
By Kelissias

https://tbcdb.com/?quest=4021

 Fortunately, this one is simple. The quest 'Counterattack!' is the last of a chain in The Barrens. It is located west of The Crossroads with the quest giver in a bunker. When a player accepts the quest, it should trigger a bunch or horde Orc warriors and Troll axethrower NPC's as well as a bunch of centaur surrounding an elite mob who is the target of this quest, but only the elite mob spawns.

 

The centaur should charge one at a time into the player and their allies, and when the non-elites are dead, the elite mob charges in. Looting his corpse completes the quest.

 

Not too complicated, and the quest is a load of fun. I'm disappointed I couldn't partake in it.

**Comment by Alucard-entropius** [comment]
Tested, there are no waves, just elite npc you have to kill for quest item. Quest requires 3 players at least, like this is doable solo.
