### ISSUE TITLE
 Ahn'Qiraj Anubisath Sentinel 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#122]
https://www.wowhead.com/npc=15264/anubisath-sentinel#comments

- When one dies, the other 3 will heal to full and gain the buff of the mob you just killed. This means the last one will have 4 buffs.

I was doing AQ40 yesterday as an arms warrior and I could confirm that if a Sentinel die with Mortal strike on it will only heal up half of the missing hp and not full. 

I dont remember this being the correct behavior on other private server and I didn't read it should work like that anywhere.

Azelen: Hmm, they use Heal Brethren to heal each other on death, it only heals for ~50k damage, I'll need to do some more researching when I have a chance.

**Comment by Alucard-entropius** [comment]
![Wow_RL4Q7n38y1](https://user-images.githubusercontent.com/62255649/81441921-ec997280-9172-11ea-85f6-d18334f06f5f.png)
Tested, works as inteded.
If one dies, it heals other 3 for set amount, but if one of 3 alive has Mortal strike as debuff, it will take only 50% healing (mechanic of Mortal strike)
