### ISSUE TITLE
Creatures of the Eco-Domes

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#13]
By Keritous

https://www.wowhead.com/quest=10427/creatures-of-the-eco-domes

 1. Whenever talbuk got tagged he despawns after 40sec, then respawns after 5mins. http://uupload.ir/files/2pv_wowscrnshot_070719_112942.jpg

The respawn time should be much shorter, since they're not killed. 

     
     
     
      Quote

    Morbain on 2007/02/21 (Patch 2.0.8)

    They "spawn" fast because you're not actually killing them, you're just putting them to sleep (as the quest description says). If you watch, they doze off then get back up around 20 seconds later.

      Quote

    By Lily (1,512 – 8·15) on 2007/02/26 (Patch 2.0.8)

    You can also go back and forth between two Talbuk Sires/Does, and tag the same ones over and over. 

    First one gets tagged, then go for the second.
    Second one gets tagged, and the first has woken up.
    Repeat, etc etc.

**Comment by Alucard-entropius** [comment]
Seems to me that just before talbuks wake up and evade to heal up, they actually appear dead and then start their 5 min respawn timer. which shouldnt happen, as game shouldnt kill them off.
