### ISSUE TITLE
Zul'jin Phase 3

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#130]
I'm not sure if this is a bug and I didn't record it but during a ZA a day or two ago I noticed that I was getting slapped with lightning not only when I cast  Prayer of Mending but each time it proc'd and hopped in the raid.  There is no mention of this in the wowwiki and the wowhead page for Zul'Jin is gone so I can't search it for comments about this.

 

I can record a video the next time I'm in there on a priest but that may not be for a week or two.

**Comment by Nextcalibur** [comment]
prayer of mending counts as a spell cast on proc.
