### ISSUE TITLE
Shade of Aran

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#139]
https://www.wowhead.com/npc=16524/shade-of-aran

The following spell Flame Wreath (http://db.excalibur.ws/?spell=30004) is completly broken on excalibur. How it should work:

 

Flame Wreath

If Flame Wreath is upcoming, the whole raid must immediately stop moving, simple as that. People must wait until the auras are clearly visible, and may only move again when they are sure they will in no way come near one of them. Melee'rs have a few seconds to move into melee range of Aran from the second Flame Wreath is announced and until he casts it; however, this requires some practice and careful timing.

The effect is triggered by the following:

Player character movement into or out of a ring

Accepting a resurrection cast by a player who is inside a ring

Using  [Reincarnation] or  [Soulstone] inside a ring

Mages'  [Blink] into or out of a ring

Druids' shapeshifting inside a ring

Shaman Elementals ( [Fire Elemental Totem],  [Earth Elemental Totem]) crossing a ring

The following do not trigger the effect:

Spell casting

Moving around inside the rings

Moving around outside the rings

Turning resulting from a spell cast (such as  [Mind Flay],  [Steady Shot] or  [Whirlwind])

Immunity/removal effects such as  [Divine Shield] or  [Cloak of Shadows] (these did initially trigger the effect)

Pets

Companions

Flame Wreath is confirmed to crit, having an estimated crit chance of 10-15%, dealing 7.000+ damage to the target.

https://wow.gamepedia.com/Shade_of_Aran#Flame_Wreath

 

How it works:
Flame Wreath is visible but deals no damage at all. You can move around, cross the lines without anything happening.

**Comment by MihawkEntropius** [comment]
Tested and working
