### ISSUE TITLE
SV Final boss Door

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#140]
I thought there was already a report for this but didnt see it so reporting it again

 

The final locked door in Steamvaults before the room with the boss Warlord Kalithresh inside requires your whole party to ALT+F4 and relog in order for it to open even though you have activated both switches behind the first 2 bosses. This looks like just a local visual issue but the door is never removed and players can not go past it without relogging.

**Comment by Alucard-entropius** [comment]
Tested, works just fine after pressing both consoles.
