### ISSUE TITLE
Strat last boss gate

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#142]
Hi,

Just as the gates in the Steamvault, the ones in Stratholme also don't always open after clearing all Ziggurats. 

I think that it happens when you kill the last out of 3 bosses far away from the gate (because you can kill them in any order).

And, just as with SV gates, this one is fixed with Alt-F4 and re-log. 
![Wo-WScrn-Shot-040219-135400](https://user-images.githubusercontent.com/63980522/79811112-31509b80-8375-11ea-8c76-c14903ee88f0.jpg)

**Comment by Alucard-entropius** [comment]
Tested, worked.
