### ISSUE TITLE
Ilidari Council

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#144]
Hi,

 

This happened at ~10% of boss' hp, though I doubt the hp plays any role here.

 

A Rogue (Veras) all of a sudden took the stairs (the ones which lead to Illidan) instead of going straight to his target after he re-appeared from Vanish.

Basically, he ran too far away on these stairs or hit a wall/ledge and all the bosses ran back, healed themselves and then aggroed at us again.

 

After this happened, the bosses stood in weird places.

 

Aerion came a bit later, but he only saw the odd boss placement, not the bug itself, unfortunately.

 

So, if you look at the screenshot, the rogue (circle) was tanked in the direction that I am looking, near the stairs.

He Vanished and upon re-appearance, ran up the stairs (not actually stairs, rather a narrow ledge behind the wall).

Yours sincerely,

Bon.

**Comment by carebot90** [comment]
![2E3F3C07-E3A4-4518-8D08-440C1D4CC0F4](https://user-images.githubusercontent.com/63980522/80207724-f8435000-862e-11ea-8d7b-20c6a3a29cd1.png)

For some reason I didn’t upload the ss

**Comment by Alucard-entropius** [comment]
It was 1 in a thousand pulls, it was easily fixable ingame. Keeping open mind if it happens again.
