### ISSUE TITLE
Dungeon npc Leash

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#146]
First from me, imo put path in 2nd plan, the npc in dungeon should never stop going after you no matter how far you go, here for you to keep them on you but must not go farther than x yards.

Good day,

 

I have been farming a lot of low level cloth in dungeons. I clear the dungeons in 1-3 pulls with my prot paladin. I have experienced a constant issue in DM, Stocks and SM thus far(I have not tested others however) my prot pally runs into issues all the time on his tanking adventures throughout TBC. I know we are suppose to be specific with the dung and issues so I will stick with Scarlet Monastery for my example. 

 

 

I have created some videos to reference by what i mean.The video is taking in SM Library.

Sometimes mobs just stand in one place and will not follow the tank if he LOS   -happens in a lot of dungs -old and new.
Sometimes a mob will start running up and down the same path again and again till you kill them.

Some mobs will reset once you are to far away.

This happens almost every dung I have run in.

 

Link to the video is here (*please watch all the way through):  https://youtu.be/Da_WROcsaSw

SM Graveyard works good most of the time

SM LIB, Arm and Cath have a lot of issues that happen in the video. The same issues happen in DM and especially stockades.

 

The time it takes to clean up the pulls is worth another run, unfortunately this is time and gold! This is my favorite way to farm gold and level guildies! Growing the guild and the server :D

 

Please any help or direction to resolving the issue would be greatly appreciated!

**Comment by Alucard-entropius** [comment]
Tested, LOS pull in mentioned dungeons works and you can gather all mobs in one place.
