### ISSUE TITLE
Kalecgos Resurrection 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#151]
If someone dies in the demon realm to the curse the dead player gets ported out of the realm on their screen, but not for others' (and their corpse isn't downside either) and they keep getting the out of range message when attempting to ress them. Observed this Friday, all players involved were horde and even after combat was over the bug persisted.

**Comment by Alucard-entropius** [comment]
IF this report is about not dying in shadow realm and not being able to ressurect by players, it is fixed and working
