### ISSUE TITLE
ZF Stairs Gauntlet

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#155]
This one is from me, there's a lot of ZF stairs reports but they are all very unclear/bad.

Talking from memories.

When you start the gauntlet, the goblin should fight a long and only go away when you speak with the human warrior after the boss is dead, then he should run away and blow the door toward last boss open.

What happens is that he run asap when you start the gauntlet and the gate open after a certain timer elapse.

**Comment by Alucard-entropius** [comment]
Gauntlet is there
