### ISSUE TITLE
Stockades Entrance

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#158]
What happens now:
At this moment when you wait for your group to assemble outside of The Stockades in Stormwind nothing happens.
 
What should happen:
Sometimes a group of Defias Rioters will come from the instance and attack the Guards and other players.
They won't survive that long and it only lasts for about 5–10 seconds.
Defias Rioters can be found in Stormwind City, breaking out of the Stormwind Stockade.
They break out every half-hour, and the guards make quick work of them, but it's not a very safe place to be as a low-level.
You will hear ~4 cell doors open and shut (usually ~1 min apart) before they come charging out from within the stockade.

**Comment by Alucard-entropius** [comment]
![Wow_qSbLPIbNp0](https://user-images.githubusercontent.com/62255649/80529529-e5ff4400-8997-11ea-9c13-1fdb11bf2d2f.png)
![LDhgl856Bu](https://user-images.githubusercontent.com/62255649/80529540-e8619e00-8997-11ea-9529-3b6cd6e2848f.png)
