### ISSUE TITLE
Karazhan trash before Moroes

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#162]
The mobs in the Grand Ballroom in Karazhan (up the stairs before Moroes) are seemingly not linked correctly resulting in massive chainpulls that sometimes gets you 2-3 and even 4 groups of mobs at once. It's even happened that while seemingly have managed to get a single packs aggro another pack comes crashing down on you mid-fight. While this might not be a huge issue for the better geared grps it certainly makes things more diffucult than the bosses for lesser geared grps. Also the mindcontrolling that certain mobs do are being casted way too often and do not work as intended either making it even worse handling the large amounts of mobs.

**Comment by Alucard-entropius** [comment]
There are few tweaks to fix about pulling packs

**Comment by Nextcalibur** [comment]
Duplicate.
