### ISSUE TITLE
Bogblossom 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#165]
This item is for a specific part of the swift flying form quest chain for druids 

https://wowwiki.fandom.com/wiki/Bogblossom

On Exc it never exploded as it should. 

I spoke with Azelen about it, he knew about it and said its one of the bugs caused by a route issue that affect a group of bugs.

**Comment by Alucard-entropius** [comment]
Tested, does not knockback, as it should

**Comment by MihawkEntropius** [comment]
https://streamable.com/2wvxnm

**Comment by MihawkEntropius** [comment]
In the video I linked I got pushed a few times but  I think it was 1/10 or so, should probably be more often.
