### ISSUE TITLE
Rough bronze shoulders

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#166]
Hi,
 
Rough Bronze Shoulders used to be Common in Vanilla.
In TBC, they were upgraded and are now Uncommon, they give extra stats.
 
On Excalibur, the stats are applied, but the item is considered to be Common, which is why you get a message "Equipping this item will bind it to you", but when you put them on -> they are still "BoE", you can take them off and trade with whoever you want.
 
Unfortunately, applying Aldor's enchant makes them BoP, so kids, don't try this at home
 
Your Forum Fidget,
Bon

**Comment by Alucard-entropius** [comment]
![Wow_cu9kyNNha2](https://user-images.githubusercontent.com/62255649/80497480-cd2c6980-896a-11ea-84e9-3cf01c98ffb1.png)
![Wow_ReLWcqYJnl](https://user-images.githubusercontent.com/62255649/80497496-d289b400-896a-11ea-8da4-998b383e7a13.png)
Tested, its still Common item without BoE message, or "Equipping this item will make it soulbound".
BUT putting shoulder enchantment WILL make it Soulbound, like any other Common shoulder item.
