### ISSUE TITLE
Fishing daily loot

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#169]
Long story short it bug sometimes: 

When fishing up the quest item for the daily fishing quest,: I click the item in the loot window,  the loot windows closes and the quest item doesn't appear in my bag. I have to fish up the quest item two to five times to get it to loot properly. This happens on two characters on different accounts, This happens several times a week, randomly. 

Replies: https://youtu.be/bXL8ANG6A-M

Crocolisk in the City again today and this time the glitch struck and then vanished on its own.  Which is to say...
 
- first cast got the crocolisk but it vanished when looted
- I continued to casting without restarting to see if the bug would be persistent
- all of the following 6 or so cast got lootable fish but no crocolisk
- last cast got the crocolisk and when I looted it, it went into my bag and the quest completed
 
Moody little bug, isn't it?

It struck again today while doing World's Largest Mudfish in Nagrand.  I made my way around the school in the lake beside Nagrand and after fishing out the school near Throne of the Elements I started catching the quest item.  The first time I clicked on the non-quest fish in the catch and the loot window closed with nothing transferring to my bags.  The second catch had the quest item again and clicking first on the non-quest fish looted the non-quest fish properly.  Clicking on the quest item/fish closed the loot window without transferring the quest item to my bags, as reported before.
 
I did a few more casts and the bug continued.  So I closed and re-launched the client as suggested by Azelen.  The bug continued.  Remembering how the bug seemed to clear on its own in Stormwind, I kept casting for a little while and then afk'd to do other things for a few minutes.  When I came back and resumed fishing I got the quest item after a few casts and it looted properly.

**Comment by Alucard-entropius** [comment]
Couldnt confirm, but got quest item few fishings in, directly into bags, no gimps.
