### ISSUE TITLE
Consecration proc

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#175]
https://classic.wowhead.com/item=21190/wrath-of-cenarius
https://www.wowhead.com/item=29305/band-of-the-eternal-sage

Hello,
 
So I got myself the two rings . One says it procs on harmful spell, the other by offensive spells, but niether equip effects are proccing on consecration. Was wondering if I'm missunderstanding something here or it's just not working as intended.

**Comment by Alucard-entropius** [comment]
Tested, Consecration doesnt proc "...on harmfull spell land..." items.
