### ISSUE TITLE
Stone Statues from Jewelcrafting have unlimited range

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#181]
title says it all. I have tested this with Rough Stone Statue and Coarse Stone Statue. Their range seems practically unlimited, as I have never managed to get outside of it before they broke. Once I used one on the zeppelin as it was taking off. The statue stayed in place while the zeppelin took off, and I kept receiving healing until zoning to the next continent.
 
I don't know what range they had in retail but I doubt it was more than maybe 100 yards. I've had these working at 1000+ yards.

**Comment by Alucard-entropius** [comment]
Tested, works as intended.
