### ISSUE TITLE
Blue Ribboned Wrapping Paper

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#187]
Hi,
 
I don't know which items does this wrapping paper hate (works fine on Uther's Strength), but I managed to lose 2 epic items: Robes of Insight and a Hood of Primal Life (+10 stamina enchant).
To be exact: I wrapped the item, the icon didn't change, I right-clicked it, moved it away, to a different bag slot, icon changed to a present, I tried to open it and it disappeared, saying Item was not Found.
Dragging items into the place where my unwrapped gift should be, relogging and resetting the UI don't help.

https://youtu.be/6oasSIT-EBw

**Comment by Alucard-entropius** [comment]
Tested with same items, Couldnt recreate bug, Tried random paper + random item, still worked. Doesnt need fixing.
