### ISSUE TITLE
Spell queue

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#189]
From patch 2.30 notes:
  Quote
Client spell cast requests are now sent to the server even if your player is already casting another spell. This eliminates the need for /stopcasting in macros to compensate for latency.
Source: https://wowwiki.fandom.com/wiki/Patch_2.3.0
 
What this means is that at patch 2.3.0 a spell queue system was implemented, meaning that if you cast a spell and keep click another spell before the spell ends, the server will pick this up and cast the next spell you clicked even though you clicked while still casting.
This will make the server a lot better especially for NA players who has more ping and this would help compensate for this. 
 
I know this will probably be a major change and potentially adding a lot of bugs to working classes like hunter's, but I think this is a necessary thing to make this server one of the best. 

https://youtu.be/FXFjvsD7VI4

**Comment by Nextcalibur** [comment]
Needs further research.
