### ISSUE TITLE
Negative reputation

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#193]
Low
Hi,
 
This doesn't feel right. 
Shouldn't the rep be Clamped at 0/36000?
 

https://i.postimg.cc/q4pzBwNX/Wo-WScrn-Shot-042019-093611.jpg?dl=1

Did you change faction maybe (not necessarily recently)? Or did you switch from Aldor to Scryers on this character (again, not necessarily recently)

Yes, that is, indeed, the reason behind this. 
I switched from Orc to BElf. 

I tried completing a random Scryers quest, it didn't decrease the reputation with Aldor any further.
Thanks!

**Comment by Nextcalibur** [comment]
Faction / Race change related. Probably wont be a problem with our new tools.
