### ISSUE TITLE
Negative rep

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#194]
Hi,
 
This doesn't feel right. 
Shouldn't the rep be Clamped at 0/36000?

https://i.postimg.cc/q4pzBwNX/Wo-WScrn-Shot-042019-093611.jpg?dl=1

Azelen : Did you change faction maybe (not necessarily recently)? Or did you switch from Aldor to Scryers on this character (again, not necessarily recently)

Yes, that is, indeed, the reason behind this. 
I switched from Orc to BElf. 

I tried completing a random Scryers quest, it didn't decrease the reputation with Aldor any further.
Thanks!

**Comment by Nextcalibur** [comment]
Invalid, unrelated to current project. We are not using the excal web tools.
