### ISSUE TITLE
Mobs repositioning after being disabled

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#197]
After the last patch i noticed, after any NPC is stunned/rooted it tries to reposition towards its aggro holder even if its not necessary and he is in range already

eg: i move towards target, stun it, and after the stun fades, the mob will move infront of me even if im in his melee range

Player: I think what he's trying to say is that let's say you are facing a mob and you stun it, then after the stun expires it will move few yards in a random direction, acting like it's actually not facing you and trying to get a proper position. This is particularly annoying for tanking since the mob may move behind you for a second, while it keeps attacking you.

**Comment by Alucard-entropius** [comment]
Tested, stun mechanic works.
