### ISSUE TITLE
Skinnable mobs

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#198]
To my memory and that of others I have spoken to, spore bats(such as those in underbog), and dragonhawks(like in tempest keep dungeons and the eye, and those in ZA) should be skinnable in all modes of those instances and in the outdoor environments in which they appear. The same issue might be happening with wolves in Hellfire instances, but I can't say I am 100% on that being a problem on Excalibur at the moment. 

Azelen: 

    http://www.wowhead.com/npc=20039/phoenix-hawk#skinning
    http://www.wowhead.com/npc=23834/amani-dragonhawk#skinning

They have skinning loot.

Note: Looks like it should have been fixed but not marked as such.

**Comment by Alucard-entropius** [comment]
Tested, with skinning level high enough, skinnable mobs in instances such as Underbog, Ramprats, Zulaman...etc do drop leathers.
