### ISSUE TITLE
Sometimes no casting animation or cast bar when casting spells

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#200]
Sometimes when casting spells the cast bar disappears and the cast animation doesnt play, but you are actually still casting.  This can happen quite rarely when normally casting as shown in this video at 3 seconds in and at 2:04.

 

https://www.youtube.com/watch?v=n0p3UTkYkUc&t=

 

I have no addons on except an event shower.  If you frame advance with . when it bugs out, you can see shortly after the bugged casts start, a spell not ready yet is displayed and the cast bar is removed, but 1.5 seconds later the spell finishes anyway.  A consistent way to recreate this bug is to cast a spell, wait until global cooldown is over, then spam /stopcasting /cast something macro 4 times like in this video

 

https://www.youtube.com/watch?v=9jMI0__q6UI

 

Another way to recreate this bug that is very doable in normal play, especially as a healer, is to cast a spell, wait until global cooldown is over, then take a step and hit a normal cast twice as shown here

 

https://www.youtube.com/watch?v=PilI6yHMGG8

 

Usually the best way to deal with this bug is to guess if the bug occured and not hit any buttons, which most of the time you can tell, but sometimes you cant and you lose a spell cast.  Another way is to just spam through it, in which case after about 1 second or so you start a new spell cast and the phantom cast is lost, like in this video

 

https://www.youtube.com/watch?v=OHgUFDgCQko

 

I'm quite sure this bug is very old.  It has been an annoyance and minor damage loss on my warlock, but has become a real problem on my healing priest.  My usual displayed latency is 160 ms.

**Comment by Alucard-entropius** [comment]
With my latency of 38, wasnt able to recreate bug, doe i deem it either fixed or latency related, please proove me wrong otherwise.
