### ISSUE TITLE
Strange gravity regarding flying.

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#202]
https://www.youtube.com/watch?v=RDKv84bs590&feature=youtu.be

What I believe is the issue is that when you fly forward and dismount you for a moment move a lot faster forward, for a brief moment. If ground interrupt that fast movement in a precise moment, you die.  

Dev: 

That's a different issue from what we understood from that video, hence is always better to read the How To before posting a bug report. We had the impression that the character couldn't fly level for some reason and was constantly going down.

We'll need to check this out, I recall something similar on retail, need to test it out someday.

The momentum after dismounting is blizzlike, the death is not intended tho, will have to be handled.

**Comment by Alucard-entropius** [comment]
Unable to recreate as in video, tried many many times. Cannot confirm it, Closing for now, but keeping open mind for specific situations.
