### ISSUE TITLE
LoS :cry:

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#203]
Hi,

 

Basically, any of the spellcasters won't chase you if you go out of their Line of Sight (move behind a wall).

 

On the screenshot, I just kept going behind the wall and back while the NPC was pathetically trying to cast something.

 

What should happen is that spellcasters should change their behaviour to melee behaviour and start chasing you if you're not in their line of sight.

Of course, it's much deeper than that and might cause even more problems, but in dungeons, it's really ruining many pulls and mobs.

It also results in some mobs standing in one place without doing anything, while standing near another pack (melee players can't get to it without aggroing nearby NPCs so ranged dps should kill the target while it stays in one place).

**Comment by Alucard-entropius** [comment]
Tested in several dungeons, working properly in general, Still, keeping open minded for specific cases!
