### ISSUE TITLE
 clipping while getting booted from an instance while sheeped. 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#204]
Not really certain where to place this in the categories so throwing it in misc.

 

You get booted from an instance (ZA to be exact), and when I was booted, I got sheeped, and when I got teleported back into shattrath aldor inn, I clipped through the floor, fell down some ridge with my body ending up around at cords 94 / 38.5

  
![EuboGf0](https://user-images.githubusercontent.com/63980522/79890872-68b85a00-8400-11ea-86a5-ffd4fe1d7530.jpg)

**Comment by Alucard-entropius** [comment]
Highly unlikely to happen on non-Xfaction server now, but if it does, we will look into it.
