### ISSUE TITLE
Soul link

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#212]
Hello everyone! I wanted to report that Soul Link is not working properly. The description reads that the effects take place when used on a pet or enslaved demon. While the effects apply normally on all warlock pets, it seems to be uncastable on enslaved demons. Should you try it on an enslaved demon the error "you don't have a pet" pops up instead. I read an older post stating the issue would be fixed in the next update. But that post is more than a year old... So I wanted to know if there are any plans for it to be fixed anytime soon or if that is even possible.

 
I'm including a screenshot showcasing exactly the issue, and one showcasing the spell in question.
 
To whomever it might concern, thanks in advance.

This is the link with the patch details ( http://wowwiki.wikia.com/wiki/Patch_2.1.0 ) and these are the segments in question if you don't wish to scroll through the whole thing;
 
Soul Link: Adjusted tooltip to explain that the damage transferred to the pet cannot be prevented. The functionality remains unchanged. This ability will now work with enslaved demons.

**Comment by Nextcalibur** [comment]
Fixed next core deployment.
