### ISSUE TITLE
Steam Vaults Door

### ISSUE THREAD

**Issue by Photosynthh** [Nextcalibur/Bugtracker#215]
Once final boss is dead door closes and you are not to go outside and reset dungeon to do again or go to next dungeon. Have to hearth to leave 

![image](https://user-images.githubusercontent.com/61897752/80927422-c1c2af00-8d6b-11ea-8f8c-03df919842a0.png)

**Comment by Alucard-entropius** [comment]
Still need to confirm with live grp of rank 0 accounts. Regular party.
