### ISSUE TITLE
Showdown

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#22]
by Manaruby

Quests:

https://www.wowhead.com/quest=10742/showdown
 

Issue:

Once you summon Goc, he will be non-interactable, making it impossible to complete the quest.

**Comment by Alucard-entropius** [comment]
QUEST WORKS FINE, but it needs a little touch to Goc's lines of text.
Rework this line: **Goc yells: Your name is as insignificant to me as the names of the thousands who have died under the might of Goc. I will crush you and $n!**

**Comment by Nextcalibur** [comment]
Alliance side AI Script missing.

**Comment by MihawkEntropius** [comment]
Note: Auto complete by GM on alliance.
