### ISSUE TITLE
Severed defender, abilities

### ISSUE THREAD

**Issue by Alucard-entropius** [Nextcalibur/Bugtracker#228]
https://www.wowhead.com/npc=20934/severed-defender#abilities

Creature not using any of 3 abilities. attacking just melee.

Selected: [Severed Defender]
SpawnId: 73755 Entry: 20934
DisplayId: 19918 (Native: 19918).
Unit Flags: 524288. Unit Flags 2: 0.

**Comment by Nextcalibur** [comment]
Fixed next restart..
