### ISSUE TITLE
[Mob behavior] Mutated Owlkin does not aggro on player characters in Azuremyst Isle

### ISSUE THREAD

**Issue by Daevek** [Nextcalibur/Bugtracker#236]
Precondition : 1 ) Player is a Dranei and has the following quest active :  "Spare Parts"
 

Description : While trying to perform the quest "Spare Parts" the player is supposed to collect the parts from Owlkin territory where the mobs are supposed to attack the player reference below from wowhead.However this is not observed.
( https://www.wowhead.com/npc=16537/mutated-owlkin)

Steps to Reproduce  : - 

1. Level up a Dranei and complete the class quest
2. Pick up the quest "Spare Parts" and move towards the quest area
3. Start walking next to the two different owlkin mobs while looting quest items

Observed behavior : Mobs do not attack the player and seem to be neutral.

Expected Behavior : Mobs should attack the player

**Comment by Nextcalibur** [comment]
Fixed next restart.
