### ISSUE TITLE
[Mob behavior] Kobold Laborer mobs are not hostile in the starting human zone

### ISSUE THREAD

**Issue by Daevek** [Nextcalibur/Bugtracker#237]
Precondition : Player starts in the human zone and works towards the quest to kill kobold laborers

Description : These mobs should be hostile towards the players in TBC but they are not observed to be hostile on the server

Reference :  https://wowwiki.fandom.com/wiki/Kobold_Laborer

They were changed to neutral after patch 3.3

Observed behavior : Mobs do not attack the player and seem to be neutral.

Expected Behavior : Mobs should be hostile by default

**Comment by Nextcalibur** [comment]
Fixed next restart.
