### ISSUE TITLE
[Mob behavior] Frostmane Troll Whelp are not hostile towards players by default

### ISSUE THREAD

**Issue by Daevek** [Nextcalibur/Bugtracker#239]
The Frostmane Troll whelp in the Dun Murogh starting area **should be hostile towards player** characters.They are part of a quest : ] The Troll Menace: Frostmane Troll Whelp slain (10)  and the players will encounter them near caves in the starting area.

Reference : https://wow.gamepedia.com/Frostmane_Troll_Whelp 

**As per this wiki post the behavior was changed from hostile->neutral after patch 3.3** 

please change the current behavior of these monster NPC's from neutral->hostile

**Comment by Nextcalibur** [comment]
Fixed next restart.
