### ISSUE TITLE
[Mob Behavior]  Chief Sharptusk Thornmantle is not acting hostile towards player

### ISSUE THREAD

**Issue by Daevek** [Nextcalibur/Bugtracker#241]
Precondition: Player is in tauren starting zone and on the quest  [5] Break Sharptusk!

Description : 

The NPC Chief Sharptusk Thornmantle is expected to be hostile towards player characters but is acting neutral

Reference 👍 
https://classic.wowhead.com/npc=8554/chief-sharptusk-thornmantle#comments

Actual behavior : Mob NPC is neutral

Expected behavior: Mob NPC should be hostile

**Comment by Nextcalibur** [comment]
Confirmed. Fixed next restart.
