### ISSUE TITLE
[Mob Behavior] Blood elf scouts are not hostile by default in Azuremyst island starting zone

### ISSUE THREAD

**Issue by Daevek** [Nextcalibur/Bugtracker#242]
Precondition : 1 ) Player is a Dranei and has the following quest active : "The Blood elves"

Description : While trying to perform the quest "The Blood elves"  the Blood elf scout mobs are supposed to attack the player, however they are acting neutral.This is the wrong behavior..in TBC the mobs were hostile by default until patch 3.3.

source : - https://wow.gamepedia.com/Blood_Elf_Scout 

Steps to Reproduce : -

Pick up the quest "The blood elves" and move towards the quest area
Start walking next to the  blood elf mobs ex : Blood elf scout
Observed behavior : Mobs do not attack the player and seem to be neutral.

Expected Behavior : Mobs should attack the player

**Comment by Nextcalibur** [comment]
Confirmed. Fixed next restart.
