### ISSUE TITLE
Terestian Illhoof - Imp 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#249]
https://www.wowhead.com/npc=15688/terestian-illhoof#abilities

He is basically not using his "summon Imp" ability. 

Not small ones, the big one, we killed it at start and he never summoned it. 

Quote from wowhead : Imp buddy buffs illhoof and needs to be nuked over and over (respawns after 30 seconds or so).

**Comment by Nextcalibur** [comment]
Should respawn every 30-45 seconds according to the scripting, needs to be tested further.

**Comment by MihawkEntropius** [comment]
Tested and working properly.
