### ISSUE TITLE
Moroes - Vanish

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#251]
https://www.wowhead.com/spell=29448/vanish

Moroes has a very clear ability, he goes in stealth for 12 seconds. 

What happens here is that if he get instantly damaged i.e. what happened to me was consecration he was standing on, he would go into stealth but instantly come out of it. 

Aoe damage should not get him out of stealth. 

https://www.youtube.com/watch?v=2jiTBXEygxg

Retail Moroes video, you can see he periodically goes into stealth and reappears after some time.

**Comment by Nextcalibur** [comment]
Confirmed

**Comment by Nextcalibur** [comment]
The spell cast is the correct one but the correct behavior should be to make him immune to damage during the vanish. Will look into a proper fix for this.

**Comment by Nextcalibur** [comment]
Fixed.

**Comment by MihawkEntropius** [comment]
Tested with consecration, not breaking Moroes stealth/Vanish.
