### ISSUE TITLE
Fleshbeast - Karazhan 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#252]
https://www.wowhead.com/npc=16595/fleshbeast#abilities

It looks like its missing Infectious Poison ability. 

Tested with a dummy toon tank and it still didnt do it, maybe requiring multiple player characters to activate.

**Comment by Nextcalibur** [comment]
The mob should be using  spells 3391, 29935 and 29939 which it seems to be doing.
