### ISSUE TITLE
Karazhan Back Door

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#253]
What's supposed to happen is when you clear Opera in Karazhan you can leave Karazhan and enter through the side/back door and skip the trash between the back door and Opera. 

Right now, you need to first clear the trash inside, till the door, open the door from the inside and then be able to zone in through the back instance portal. Basically having to unlock from the inside to access from the outside. 

Evidence: 

https://wowwiki.fandom.com/wiki/Opera_event

Quote : Successfully completing the Opera also enables you to reach the side entrance, making wipe recovery much quicker. Prior to patch 3.2.0 the door opened automatically when the event was completed, enabling raids to skip several trash pulls by leaving and reentering.

and 

https://www.youtube.com/watch?v=dl0lER5Ifew

Quote: Once your raid has cleared past the Opera it becomes shorter to enter the instance through the Karazhan back door in order to make attempts on Curator and Nightbane "

**Comment by Scalebeard** [comment]
Not a bug, but a fix that isn't blizzlike.

Backdoor wasn't supposed to open after defeating the Opera boss, but that was never resolved until after the expansion was long over. While the current state is the intended one, it is not blizzlike.

**Comment by Bart748** [comment]
It makes no sense for a shortcut to open after a boss instead of opening it yourself. We will keep the current system to make the content a bit harder/longer.
