### ISSUE TITLE
Neutral mobs in low level places.

### ISSUE THREAD

**Issue by Sowarz** [Nextcalibur/Bugtracker#254]
As far as i know the vermin and demons in orcish cave should be hostile not neutral in tbc - although that might've changed in 2.4.3. i recall on every bc server i played on they were hostile.

**Comment by Sowarz** [comment]
![image](https://user-images.githubusercontent.com/65663147/82448256-c4cad880-9aa9-11ea-8fb6-096e676c5b66.png)

**Comment by MihawkEntropius** [comment]
https://www.youtube.com/watch?v=cDcnmtEU4uE

This should be a video from classic wow , they are all red. Could be they were changed later but I didnt find any evidence to support that.

**Comment by Nextcalibur** [comment]
Fixed next restart.
