### ISSUE TITLE
Mottled Boar drops Undamaged Hippogryph Feather

### ISSUE THREAD

**Issue by Jezofine** [Nextcalibur/Bugtracker#256]
Mottled Boars in Valley of Trials (Durotar) should not drop [Undamaged Hippogryph Feather] (id 10450).

**Comment by Nextcalibur** [comment]
![image](https://user-images.githubusercontent.com/62207566/82457280-8509ee00-9ab5-11ea-8b85-c75b90d22368.png)

I'd guess it's from the droprates being cranked up atm.
