### ISSUE TITLE
Missing mob.

### ISSUE THREAD

**Issue by Sowarz** [Nextcalibur/Bugtracker#259]
![image](https://user-images.githubusercontent.com/65663147/82470024-1896eb00-9ac5-11ea-8443-b1d6e09df1ef.png)
There is a warlock mob missing, who spawns under the tent on the screenshot, im 99% sure there should be a mob with voidwalker there, i always remember pulling him first.

**Comment by Sowarz** [comment]
https://www.youtube.com/watch?v=0XgHkGH1mBo 
1:25 u can see the missing mob with his pet in the tent behind fizzle

**Comment by MihawkEntropius** [comment]
https://www.youtube.com/watch?v=0XgHkGH1mBo   skip to 1:05 ~

**Comment by MihawkEntropius** [comment]
Also, the voidwalkers are minions of 

https://classic.wowhead.com/npc=3198/burning-blade-apprentice#abilities

**Comment by Nextcalibur** [comment]
Fixed.
