### ISSUE TITLE
[Warlock][Pet][Imp] doesn't move to cast

### ISSUE THREAD

**Issue by warlocksteve** [Nextcalibur/Bugtracker#263]
Imp won't move to attack when it doesn't have LoS.  If it is behind a hill or something it won't run to somewhere where it can cast, and then attack.

**Comment by warlocksteve** [comment]
This is also occurring with the Voidwalker.  Will not move to attack unless it has LoS.

**Comment by MihawkEntropius** [comment]
Imp ID : 416 
Voidwalker ID : 1860

**Comment by Azelen** [comment]
Can't confirm. Works as intended for me, except for when pet cannot find path to its target, but that is pathfinder problem not pet AI logic.
