### ISSUE TITLE
portals of the legion

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#27]
https://tbcdb.com/?quest=5581

Minor issue

 

Activating a portal is fine, mob spawns as should and kil gives credit. Issue is portal resets to unused state within a few seconds. Blizzard had this set at around 5-10 minutes to stay in a used state.

 

As currently is quest is far too easy requiring a camp of the one portal once only

**Comment by Alucard-entropius** [comment]
Current respawn timer is 5 mins.
