### ISSUE TITLE
[NPC] Underbog - Trash

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#272]
https://streamable.com/9j7s2x

https://streamable.com/nc9ond 
as you can see one gets left behind.

https://streamable.com/u87wh9

https://streamable.com/ngob5h

https://streamable.com/1ybjf3

**Comment by Bart748** [comment]
Again please provide more information.
Information like:
NPCs
1. <spawn id>
2. <spawn id>
3. <spawn id>
should be linked to NPC <spawn id>
<link>

something along those lines.
Thank you

**Comment by Alucard-entropius** [comment]
Selected: [Fen Ray]
[21:18:58]SpawnId: 95404 Entry: 17731 Spawned Entry: 20173 (Heroic)
[21:18:58]DisplayId: 19403 (Native: 19403).
[21:18:58]Unit Flags: 64. Unit Flags 2: 0.

^This mob, part of patrol is falling through textures for a little bit.
