### ISSUE TITLE
[NPC] Ramparts - Trash

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#273]
https://streamable.com/j1rt0m
Skip to 0:35

https://streamable.com/pbnss7

https://streamable.com/d8ro4s

https://streamable.com/hoso5u

https://streamable.com/577ssn

https://streamable.com/h7da7m

https://streamable.com/hxab5h

https://streamable.com/7yzgk2

**Comment by Bart748** [comment]
Please add a correct description of the problem.  Posting videos is not the correct way to do this, yes it helps but please also add the correct informaton
