### ISSUE TITLE
Quivers Improperly Calculating Haste

### ISSUE THREAD

**Issue by IceWaterKraken** [Nextcalibur/Bugtracker#290]
Tested with Melmorta's Twilight Longbow and Skyfire Hawk Bow. Different arrow types used. Second quiver purchased.

The 15% attack speed is not being applied.  I swapped to Thori'dal and tested that, and the 15% attack speed is being applied to that. 

Timestamps for combat log would be helpful, but im unaware of any TBC mod that tracks that. I tested using a stopwatch, so its not just a UI error/quartz error. 

![WoWScrnShot_052820_080441](https://user-images.githubusercontent.com/41876225/83145540-8b522880-a0ba-11ea-83ba-3a46aecf3fb7.jpg)

**Comment by IceWaterKraken** [comment]
Steps to replicate and fix bug:

Equipping Thori'dal bugs out the quiver slot. 

Process:

Use regular bow, quiver works.

Equip Thori'dal, remove it. Go back to a regular bow.

Quiver no longer functions.

Removing the quiver from the bag slot and re-equipping it fixes the issue.

**Comment by MihawkEntropius** [comment]
Fixed
