### ISSUE TITLE
Enchant Gloves: Agility

### ISSUE THREAD

**Issue by IceWaterKraken** [Nextcalibur/Bugtracker#293]
Glove Agility Enchants are from Classic, but will be used by certain classes in TBC so should probably be added to the vendor for testing. 

15 Agility comes out of AQ40, but was added into TBC in patch 2.2 with different material requirements.  Would suggest just adding the enchant to the  Shattrath vendor rather than making the pattern available available on reputation vendor.

**Comment by MihawkEntropius** [comment]
Item ID : 20731

**Comment by Scalebeard** [comment]
Gloves - Superior Agility sadly doesn't exist as an ready2enchant item that could be added to the vendor. However, we do have maxed out Horde and Alliance Enchanters prepared. Tag Scalebeard on Discord and ask to have your gloves enchanted the old fashioned way.
