### ISSUE TITLE
[NPC][Pathing] Zalduun

### ISSUE THREAD

**Issue by Synathy** [Nextcalibur/Bugtracker#337]
This priest trainer Zalduun has been walking over an obstacle but also over his injured people! A priest walking over people can't be tolerated in our infirmary!

https://tbcdb.com/?npc=16502

https://cdn.discordapp.com/attachments/714233789521330197/720110079369805885/2020-06-09_22-55-14.mp4

**Comment by Bart748** [comment]
Fixed pathing off Zalduun. His patients will be reliefed.

**Comment by Synathy** [comment]
It's fixed!
![653346496569409546](https://user-images.githubusercontent.com/22718174/84610337-3cf9a380-ae88-11ea-8492-f6b3a6cf412a.png)
