### ISSUE TITLE
[NPC] Talaara is way too close to a generic guard

### ISSUE THREAD

**Issue by Synathy** [Nextcalibur/Bugtracker#346]
![image](https://user-images.githubusercontent.com/22718174/84572193-8520a500-ad66-11ea-9382-4351e04c92af.png)
As you may see Talaara, she's not scared of the covid thing. You may look on wowhead about how far she keep her distances from guards. :)

https://www.wowhead.com/npc=19001/talaara#screenshots

**Comment by Bart748** [comment]
Moved Guard away from Talaara

**Comment by Synathy** [comment]
It's fixed! Don't forget to remove the tag :D
