### ISSUE TITLE
[NPC] Mana Tombs (normal) - Trash Respawn

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#350]
https://streamable.com/nse6mo

https://streamable.com/4n65a3

Arost footage - https://www.youtube.com/watch?v=UB5fQDI_J7g  

The npc-s have a weirdly short respawn timer. 

Its not specific to a certain type of NPC, some npc-s of same type/name dont do it.

**Comment by Bart748** [comment]
Newly added NPCs have a respawn timer of 30 seconds, Changed it to 1 day
