### ISSUE TITLE
Fel Spirits Quest in Hellfire Peninsula

### ISSUE THREAD

**Issue by cronker** [Nextcalibur/Bugtracker#353]
It appears that the Anchorite piece that is dropped in order to get the fel spirits out of the orcs at Gor'Gaz Outpost will only activate on the orcs in it's direct vicinity when it is placed. Bringing other orcs over to it after the initial drop will not cause it to allow fel spirits to be pulled from the orcs.

**Comment by MihawkEntropius** [comment]
https://www.wowhead.com/quest=10909/fel-spirits

https://streamable.com/v5cdoq

For the future, please state the name of the quest, preferably with a link. 

The more data you give the easier/faster the dev will be able to fix. 


Cheers for reporting in any case!

**Comment by cronker** [comment]
Apologies, I put the quest in the Title. I'll try and give more info next time

**Comment by MihawkEntropius** [comment]
https://github.com/Nextcalibur/Bugtracker/issues/8

Duplicate.
