### ISSUE TITLE
[NPC][Ability] Arcane Servant - Arcane Explosion

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#373]
https://www.wowhead.com/npc=20478/arcane-servant#abilities

This npc is summoned by 
https://www.wowhead.com/npc=20059/sunseeker-netherbinder

They should do
https://www.wowhead.com/spell=22271/arcane-explosion

Example of summoned pet
Selected: Arcane Servant
Entry: 20478

Example of Sunseeker Netherbinder summoning them
Selected: [Sunseeker Netherbinder]
SpawnId: 83194 Entry: 20059

**Comment by Azelen** [comment]
![зображення](https://user-images.githubusercontent.com/667107/119380720-b5d4c280-bcc9-11eb-843f-40982e48410a.png)
They only cast Arcane Explosion when killed.
