### ISSUE TITLE
[Quest] Unexpected Results

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#392]
https://classic.wowhead.com/quest=8488/unexpected-results

Quest ID 8488 but you will need to complete 8487 first

https://streamable.com/vqo74h  skip to 2:16 

If the quest is accepted while the npc-s are stationed/patrol around the spawn location of the ambush npc-s for the quest the player is going to have to deal with 4-6 instead of just 3 as its supposed to be. 

I believe its best to relocate the spawn on the other side of the building, on the left where there's no NPC.

**Comment by Nextcalibur** [comment]
Fixed.
