### ISSUE TITLE
NPC in Shattrath City near flight master not present.

### ISSUE THREAD

**Issue by t0n1n3** [Nextcalibur/Bugtracker#395]
Some NPCs in Shattrath City near flight master are not present. They usually are standing in groups and fighting each other. Reference video - https://youtu.be/AISl3XjG9sw?t=32

**Comment by MihawkEntropius** [comment]
https://www.wowhead.com/npc=25136/shattered-sun-trainee 

2.4 NPC , part of the shattered sun.
