### ISSUE TITLE
[NPC][Ability][Mechanar] Bloodwarder Centurion - Melt Armor

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#399]
https://www.wowhead.com/npc=19510/bloodwarder-centurion#abilities

Not usingability melt armor, also mentioned in https://wow.gamepedia.com/Bloodwarder_Centurion

NPC ID 19510

**Comment by Azelen** [comment]
They have random set of abilities. Some may use Melt Armor, while others not.
