### ISSUE TITLE
[NPC][Ability][Mechanar] Bloodwarder Slayer - Chilling touch 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#400]
https://wow.gamepedia.com/Bloodwarder_Slayer
https://www.wowhead.com/npc=19167/bloodwarder-slayer#abilities:mode=heroic

Both mention he should be doing chilling touch but he is not. 

NPC ID 19167

**Comment by Azelen** [comment]
They have random set of abilities. Some may use Chilling Touch, while others not.
