### ISSUE TITLE
[NPC][Ability][Mechanar] Nethermancer Sepethrea - Frost Attack

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#402]
https://www.wowhead.com/npc=19221/nethermancer-sepethrea/heroic-encounter-journal#abilities:mode=heroic
https://wow.gamepedia.com/Nethermancer_Sepethrea

She is not using "Frost Attack" 

NPC ID 19221

**Comment by Azelen** [comment]
![зображення](https://user-images.githubusercontent.com/667107/119380022-dc462e00-bcc8-11eb-8864-d7ad069dee66.png)

**Comment by Azelen** [comment]
This is a proc-based ability, so it is random.
