### ISSUE TITLE
[NPC][Ability][Mechanar] Mechano-Lord Capacitus - Reflective damage shield & Reflective magic shield

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#404]
https://www.wowhead.com/npc=19219/mechano-lord-capacitus#abilities
https://wow.gamepedia.com/Mechano-Lord_Capacitus

Reflective Magic Shield — Mechano-Lord Capacitus surrounds himself in a protective shield that reflects 100% of all harmful spells for 10 sec.
Spell shadow antishadow.png  Reflective Damage Shield — Mechano-Lord Capacitus surrounds himself with a protective shield that inflicts 550 Arcane damage to melee attackers when hit.

Not doing either ability. 

NPC ID 19219

**Comment by Azelen** [comment]
https://www.wowhead.com/npc=19219/mechano-lord-capacitus#comments:id=31939
