### ISSUE TITLE
[NPC][Ability][Botanica]  Bloodwarder Greenkeeper - Nature Shock

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#405]
https://www.wowhead.com/npc=18419/bloodwarder-greenkeeper#abilities:mode=heroic
https://wow.gamepedia.com/Bloodwarder_Greenkeeper

Nature Shock - Hurls a bolt of lightning at an enemy, inflicting Nature damage.

Not being used. 

NPC ID 18419

**Comment by Bart748** [comment]
Updated eventflags.

**Comment by Nextcalibur** [comment]
Still not working.

**Comment by tonine-entro** [comment]
NPC casting the ability and inflicts nature damage. Works on both normal and heroic
![image](https://user-images.githubusercontent.com/67378152/86398398-285c3e80-bcc3-11ea-87c9-b855ca69756d.png)
