### ISSUE TITLE
[NPC][Botanica][Ability] Sunseeker Botanist - Rejuvenate plant & Nature's Rage

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#407]
https://www.wowhead.com/npc=18422/sunseeker-botanist#abilities

Increases a nearby plant's size by 50%, attack speed by 100% and the Physical damage it deals by 100% for 10 sec.
Heals an ally every 1 sec. for 25 sec.

Neither ability is used on the Greater Flayer 

NPC ID 

Greater Flayer - 19557
Sunseeker Botanist - 18422

**Comment by Bart748** [comment]
Target was apparently wrong, changed target.

**Comment by tonine-entro** [comment]
NPC casts Rejuvenate Plant but plant is not being healed.
NPC not casting other abilities.

**Comment by Bart748** [comment]
what other NPC's heal a target so I have a reference?

**Comment by Bart748** [comment]
Changed Target again, should be working now.

**Comment by Nextcalibur** [comment]
Working.
