### ISSUE TITLE
[NPC][Ability][Botanica] Sunseeker Channeler - Sunseeker Blessing 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#409]
https://www.wowhead.com/npc=19505/sunseeker-channeler#abilities

https://www.youtube.com/watch?v=QcrD3My_G5Q  6:26

I believe the Physical damage buffs are an aoe buff they are doing before the start of combat to anyone near them.

1.Increases the caster's attack speed by 50% and the Physical damage it deals by 125 for 30 sec. 

2.Increases the caster's attack speed by 50% and the Physical damage it deals by 125 for 1 min.

3. Bestows the blessing of the Sunseeker upon the target, healing them and all nearby allies.

Note: I dont know why there's 1 that is 30 and 1 that is 60seconds when they are basically the same. 

NPC ID 19505

**Comment by Bart748** [comment]
Perhaps one buff is heroic, the other Normal?
Added Spell=34222 Sunseeker Blessing to Sunseeker Channeler (Normal&Heroic (NPC=19505), Cast Sunseeker(34222) blessing in combat every 120s (2min)
Added listener to cast Sunseeker Blessing (34173) when Sunseeker Blessing (34222) is casted. (need confirmation listener works)

**Comment by tonine-entro** [comment]
NPC not casting Sunseeker Blessing in normal and Heroic.

**Comment by Bart748** [comment]
Changed Target to TARGET_T_SELF
Added Heroic version

**Comment by tonine-entro** [comment]
[FIXED]
![image](https://user-images.githubusercontent.com/67378152/85900365-581bca00-b81d-11ea-9a32-b314d6a73980.png)
