### ISSUE TITLE
[NPC][Ability] Arcatraz Warder - Improved Wing Clip

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#411]
https://www.wowhead.com/npc=20859/arcatraz-warder#abilities
https://wow.gamepedia.com/Arcatraz_Warder

Not using that ability.

**Comment by Bart748** [comment]
Added spell=35963 Improved Wing Clip to Arcatraz Warder (Normal) (npc=20859): Cast 1,5(GCD), 3s after combat/cycle started, repeat every 15-30s

Added spell=35963 Improved Wing Clip to Arcatraz Warder (Heroic) (npc=20859): Cast 1,5(GCD), 3s after combat/cycle started, repeat every 15-30s
Added spell=38812 Infected Blood to Arcatraz Defender (Normal) (npc=20857): When Target has no aura "Infected Blood", Arcatraz Defender will cast Infected Blood after 3-5s

**Comment by tonine-entro** [comment]
[Partially FIxed]
Improved Wing Clip working fine in both normal and heroic

Casts Infected Blood onto itself

**Comment by Bart748** [comment]
Changed EffectImplicitTargetA1 from TARGET_UNIT_CASTER to TARGET_UNIT_ENEMY for spell: Infected Blood

**Comment by tonine-entro** [comment]
[FIXED]
Now casting on enemy.
![image](https://user-images.githubusercontent.com/67378152/85899668-0757a180-b81c-11ea-94ce-d5b29181e139.png)
