### ISSUE TITLE
[NPC][Ability] Arcatraz Defender - Immolate & Infected Blood

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#412]
https://www.wowhead.com/npc=20857/arcatraz-defender#abilities:mode=heroic
https://wow.gamepedia.com/Arcatraz_Defender

Missing both abilities.

**Comment by Bart748** [comment]
Added spell=36638 Immolate to Arcatraz Defender (Normal) (npc=20857): When Target has no aura "Immolate", Arcatraz Defender will cast immolate after 3-5s

Added spell=38806 Immolate to Arcatraz Defender (Heroic) (npc=20857): When Target has no aura "Immolate", Arcatraz Defender will cast immolate after 3-5s
Added spell=38812 Infected Blood  to Arcatraz Defender (Normal) (npc=20857): When Target has no aura "Immolate", Arcatraz Defender will cast Infected Blood aftrer 3-5s

**Comment by tonine-entro** [comment]
[Partially Fixed]
Immolate ability working.
NPC casting Infected Blood on itself.

**Comment by Bart748** [comment]
Changed EffectImplicitTargetA1 from TARGET_UNIT_CASTER to TARGET_UNIT_ENEMY

**Comment by tonine-entro** [comment]
[FIXED]
Now casted on enemy.
![image](https://user-images.githubusercontent.com/67378152/85899561-daa38a00-b81b-11ea-8bc2-cff08bf76fa9.png)
