### ISSUE TITLE
[NPC][Ability] Entropic Eye - Missing Abilities

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#413]
https://www.wowhead.com/npc=20868/entropic-eye#abilities
https://wow.gamepedia.com/Entropic_Eye

The abilities he is not doing 
Hex 
Arcane Bolt
Fireball
Frostbolt
Shadow Bolt
Poison Bolt

**Comment by Bart748** [comment]
Added spell=36712 Arcane Bolt, Spell=36711 Fire Bolt, Spell=36710 Frost Bolt to Entropic (Normal) (npc=20868): Random Cast 8-13s after combat/cycle started, repeat every 14-21 seconds,
Added spell=36700 Hex, Spell=36713 Poison Bolt, Spell=36714 Shadow Bolt to Entropic (Normal) (npc=20868): Random Cast 8-13s after combat/cycle started, repeat every 14-21 seconds,

Added spell=38823 Arcane Bolt, Spell=38824 Fire Bolt, Spell=38826 Frost Bolt to Entropic (Heroic) (npc=20868): Random Cast 8-11s after combat/cycle started, repeat every 14-18 seconds,
Added spell=36700 Hex, Spell=38827 Poison Bolt, Spell=38825 Shadow Bolt to Entropic (Heroic) (npc=20868): Random Cast 8-11s after combat/cycle started, repeat every 14-18 seconds

**Comment by tonine-entro** [comment]
NPC now casting all spells,
