### ISSUE TITLE
[NPC][Ability] Eredar Deathbringer - Diminish Soul

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#414]
https://www.wowhead.com/npc=20880/eredar-deathbringer#abilities
https://wow.gamepedia.com/Eredar_Deathbringer

Not using this ability.

**Comment by Bart748** [comment]
Added spell=36789 Diminish Soul to Eredar Deathbringer (Normal) (npc=20880): 0-0s after combat/cycle started, every 5-10 seconds,
Added spell=38848 Diminish Soul to Eredar Deathbringer (Heroic) (npc=20880): 0-0s after combat/cycle started, every 5-10 seconds,

**Comment by tonine-entro** [comment]
![image](https://user-images.githubusercontent.com/67378152/85598751-83f64e80-b669-11ea-9cb3-90b857023466.png)

NPC doesn't cast Diminish Soul

**Comment by Bart748** [comment]
![image](https://user-images.githubusercontent.com/15981160/85834025-f9aa0980-b792-11ea-920d-a556c9734b4c.png)

Seems to be working correctly
