### ISSUE TITLE
[NPC] Arcatraz - Skulking Witch 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#415]
https://wow.gamepedia.com/Skulking_Witch
https://www.wowhead.com/npc=20882/skulking-witch#comments

Its missing. 

I listed the locations of this npc and it has shown me 1 location, teleported to that location and there was nothing. 

A comment on wowhead say there should be 2 of them, "If you are trying to solo this instance, watch out since there are two of these invisible mobs"

They are in the room of Dalliah the Doomsayer and Wrath-Scryer Soccothrates

**Comment by Bart748** [comment]
Changed Scripted 01 of NPC 20882: Cast Greater Invisibility Out of Combat: Event_Type from Combat to Out of Combat.
Problem: Infinite combat loop of invisibility

**Comment by Bart748** [comment]
Need location for second Skulkin Witch.

**Comment by MihawkEntropius** [comment]
https://www.youtube.com/watch?v=ZuJZi5pkhYo

15:15

If we are to believe this footage the first one was near the door (could be its patrolling in front of the door between the two sides) and second one was in the area between the 2 bosses.

**Comment by tonine-entro** [comment]
[Fixed]
2 Skulking Witch are present in the room. One near the door and another near Dalliah boss NPC.

**Comment by MihawkEntropius** [comment]
They dont seem invisible to me now, at all.
