### ISSUE TITLE
[NPC][Ability]Sargeron Archer - Scatter Shot 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#416]
https://www.wowhead.com/npc=20901/sargeron-archer#abilities:mode=heroic

Not using these  Scatter Shot

**Comment by Bart748** [comment]
Added spell=23601 Scatter Shot to Sargeron Archer (Normal) (npc=20902): 1,5(GCD)-3s after combat/cycle started, every 15-30 seconds,
Added spell=23601 Scatter Shot to Sargeron Archer (Heroic) (npc=20902): 1,5(GCD)-3s after combat/cycle started, every 15-30 seconds,

**Comment by tonine-entro** [comment]
The debuff is removed as soon as the counter reaches 2s. 
Video Link - https://cdn.discordapp.com/attachments/677454223155134464/725353323464753272/World_Of_Warcraft_2020.06.24_-_19.42.49.02.mp4

**Comment by Bart748** [comment]
spell=23601 Scatter Shot:
A short range shot that deals 50% of weapon damage and disorients the target for 4 sec. Any damage caused removes this effect.
Looks to be working just fine
