### ISSUE TITLE
[NPC][Ability] Sargeron Hellcaller - Hell Rain

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#417]
https://www.wowhead.com/npc=20902/sargeron-hellcaller#abilities

Not using Hell Rain

**Comment by Bart748** [comment]
Added spell=36829 Hell Rain to Sargeron Hellcaller (Normal) (npc=20902): 8-14s after cycle started, every 18-24 seconds,
Added spell=38917 Hell Rain to Sargeron Hellcaller (Heroic) (npc=20902): 8-14s after cycle started, every 18-24 seconds,

**Comment by t0n1n3** [comment]
Tested
Working fine.

**Comment by tonine-entro** [comment]
Tested, working fine
Closing the issue
