### ISSUE TITLE
[NPC][Ability] Phase Hunter - Back Attack 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#418]
https://www.wowhead.com/npc=20906/phase-hunter#abilities

This is one of the adds before the last boss in Arcatraz Heroic, he is not using his Back Attack ability.

**Comment by Bart748** [comment]
Are you 100% sure about that. The creature has the ability in the script:
100% chance to cast warp after 1-3 seconds, every 19-25 seconds, also cast back attack against hostile target.

**Comment by MihawkEntropius** [comment]
![WoWScrnShot_051620_173018](https://user-images.githubusercontent.com/65174823/85510388-8d46d300-b5f7-11ea-8381-499f740a02f5.jpg)
![WoWScrnShot_051620_173106](https://user-images.githubusercontent.com/65174823/85510392-8ddf6980-b5f7-11ea-8e5a-0c555e81de9a.jpg)

**Comment by Bart748** [comment]
![image](https://user-images.githubusercontent.com/15981160/85833419-fb270200-b791-11ea-85ed-6041dca9fd51.png)

**Comment by Bart748** [comment]
Looks like it works to me.
Changed caster permission from nothing to Force Cast & Interrupt Previous Cast
