### ISSUE TITLE
Cloak of Shadows Removing Flare debuff

### ISSUE THREAD

**Issue by KikoIsHere** [Nextcalibur/Bugtracker#420]
Cloak of Shadows Should Not Remove Flare debuff. 

https://wowwiki.fandom.com/wiki/Cloak_of_Shadows

"Will not provide the rogue immunity to a Hunter's Flare ability."

**Comment by Azelen** [comment]
https://wowwiki-archive.fandom.com/wiki/Cloak_of_Shadows?oldid=1611395 TBC version of this article says it provides immunity against hunter's Flare.
