### ISSUE TITLE
[NPC][Ability] Shattered Hand Warhound - Furious Howl

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#423]
https://www.wowhead.com/npc=17280/shattered-hand-warhound#abilities
https://wowwiki.fandom.com/wiki/Shattered_Hand_Warhound

Not doing ability Furious Howl

**Comment by Bart748** [comment]
Changed target of Furious Howl from TARGET_T_HOSTILE to TARGET_T_SELF

**Comment by Bart748** [comment]
Changed target of Furious Howl from TARGET_T_HOSTILE to TARGET_T_SELF

**Comment by MihawkEntropius** [comment]
Working
