### ISSUE TITLE
[NPC][Ability]Bleeding Hollow Archer - Aimed Shot

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#424]
https://www.wowhead.com/npc=17271/bonechewer-destroyer#abilities:mode=heroic
https://wowwiki.fandom.com/wiki/Bleeding_Hollow_Archer

Not using aimed shot.

**Comment by Bart748** [comment]
Bleeding Hollow Archer should cast aimed shot in N/H, 12.1s-15.3s after combat started, 13.3-18.2s repeat.
Can someone confirm this, if the spell is blocked I can force cast it.

**Comment by Bart748** [comment]
Archer (NPC=17270)

**Comment by tonine-entro** [comment]
Working
![image](https://user-images.githubusercontent.com/67378152/85919765-01010e00-b88c-11ea-9046-466df8007fe8.png)
