### ISSUE TITLE
[NPC][Ability] Fel Orc Neophyte - Charge

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#428]
https://www.wowhead.com/npc=17429/fel-orc-neophyte#abilities:mode=heroic

Does not charge.

**Comment by Bart748** [comment]
Fel Orc Neophyte does cast Charge: Targets a random unit from the threat list excluding the one with the most threat

**Comment by tonine-entro** [comment]
[Fixed]
![image](https://user-images.githubusercontent.com/67378152/85899275-784a8980-b81b-11ea-9a91-6edb8ab07ce3.png)
