### ISSUE TITLE
[NPC][Ability] Shattered Hand legionnaire - Enrage & Aura Discipline & Pummel

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#429]
https://www.wowhead.com/npc=16700/shattered-hand-legionnaire#abilities:mode=heroic

It looks like all 3 are missing.

**Comment by Bart748** [comment]
Added Ability Aura of Discipline, Enrage and Pummel to Shattered Hand Legionnaire

**Comment by tonine-entro** [comment]
[Fixed]
Pummel added.
![image](https://user-images.githubusercontent.com/67378152/85898741-7207dd80-b81a-11ea-986b-cc41ecca498c.png)
Aura added
![image](https://user-images.githubusercontent.com/67378152/85898760-7af8af00-b81a-11ea-92f7-5fb2356b435d.png)
Enrage added
![image](https://user-images.githubusercontent.com/67378152/85898818-92d03300-b81a-11ea-870d-a453a5c5f442.png)
