### ISSUE TITLE
[NPC][Ability] Shattered Hand Sharpshooter - Serpent sting & Scatter Shot

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#430]
https://www.wowhead.com/npc=16704/shattered-hand-sharpshooter#abilities

https://wow.gamepedia.com/Shattered_Hand_Sharpshooter

Wow.gamepedia and some other sites dont mention Serpent sting like Wowhead does, didn't find any hard evidence to confirm Serpent sting beside Wowhead.com 

Scatter shot is missing no doubt it should be used.

**Comment by Bart748** [comment]
Add ability Shatter shot to Shattered Hand Sharpshooter.
Discuss if Serpent Sting should be added.
Can be added N, H or N/H
Could be random cast between Serpent and Viper
Could be seperate spell

**Comment by tonine-entro** [comment]
NPC Scatter shot added for both normal and HC
![image](https://user-images.githubusercontent.com/67378152/85898240-8eefe100-b819-11ea-97e5-3504ecbcba6f.png)
