### ISSUE TITLE
[NPC][Ability] Creeping Ooze & Creeping oozeling - Sticky Ooze

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#431]
https://www.wowhead.com/spell=30494/sticky-ooze

Both NPCs are not using this ability, they are in the same Pack in Shattered Halls

**Comment by Bart748** [comment]
Changed casted spell from 30492 to 30494 Sticky Ooze for Creeping Ooze (17356, 17357)

**Comment by MihawkEntropius** [comment]
Working.
