### ISSUE TITLE
[NPC][Ability] Coilfang Slavehandler - Slap!

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#432]
https://www.wowhead.com/npc=17959/coilfang-slavehandler#abilities

Not using "Slap!" ability.

**Comment by Bart748** [comment]
Added ability Slap to Coilfang Slavehandlers

**Comment by tonine-entro** [comment]
[FIXED]
![image](https://user-images.githubusercontent.com/67378152/85897966-04a77d00-b819-11ea-99c1-d027865b70a1.png)
