### ISSUE TITLE
[NPC][Ability] Dreghood Slave - Frenzy

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#434]
https://www.wowhead.com/npc=17799/dreghood-slave#abilities

Frenzy is not used at low hp.

**Comment by Bart748** [comment]
Added Ability Enrage to dreghood slave at 30% hp

**Comment by tonine-entro** [comment]
[Fixed]
![image](https://user-images.githubusercontent.com/67378152/85897817-bb572d80-b818-11ea-8cb2-eae02728f5bc.png)
