### ISSUE TITLE
[NPC][Ability] Bog giant - Trample

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#436]
https://www.wowhead.com/npc=17723/bog-giant#abilities:mode=normal

Not using trample

**Comment by Bart748** [comment]
Bog Giant should use Trample 7-12s after combat started, 10-15 repeat, on self. Could be that the ability is cancelled by Fungal Decay. Can someone confirm this?

**Comment by MihawkEntropius** [comment]
Tested, working.
