### ISSUE TITLE
[NPC][Ability] Murkblood Healer - Prayer of Healing

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#437]
https://www.wowhead.com/npc=17730/murkblood-healer#abilities

He has 2 other heals that he used but he never used Prayer of Healing, probably missing.

**Comment by Bart748** [comment]
Murkblood healer casts Prayer of Healing then his health is below 15%, 15-20s repeat.

**Comment by MihawkEntropius** [comment]
He is using it now.
