### ISSUE TITLE
[NPC][Ability] Murkblood Oracle - Missing Abilities 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#438]
https://www.wowhead.com/npc=17771/murkblood-oracle#abilities:mode=heroic

Amplify damage - Missing
Demon Armor - Missing  (wow gamepedia state only HC)
Frosta Nova - Missing (wow gamepedia state only HC)
Shadow Bolt - Missing (wow gamepedia state only HC)

Additionally : https://wow.gamepedia.com/Murkblood_Oracle

Mention he should do Corruption as well.  Only on heroic!

**Comment by Bart748** [comment]
Should Amplify Damage 3-9 seconds after start combat, 15-25s repeat (N/H) (50% chance)
Murkblood Oracle casts Elemental Armor right now. (source **https://tbcdb.com/?npc=17771#abilities**) Need more research on this
Frost Nova and Shadow Bolt seem to be a N/H spell. Different IDs for each.
Spell IDs from https://tbcdb.com/?npc=17771#abilities match the database IDs

**Comment by MihawkEntropius** [comment]
https://www.youtube.com/watch?v=RpVoq5SScl0  13:38  the npc has Demon armor pre buffed on him.

**Comment by Bart748** [comment]
changed Elemental armor to demon armor.

**Comment by Nextcalibur** [comment]
Fixed.
