### ISSUE TITLE
[NPC][Ability] Cabal Ritualist - Dispell Magic

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#440]
https://www.wowhead.com/npc=18794/cabal-ritualist#abilities:mode=heroic
https://wow.gamepedia.com/Cabal_Ritualist

They are not using dispell magic, tested with blessing of kings.

**Comment by Bart748** [comment]
Please read the spells as well before you add them here.
"Dispels magic on an **Ally**, removing 1 harmful spell"

**Comment by MihawkEntropius** [comment]
My bad there, didn't read properly, tested their ability with player corruption spell and they not removing it.

https://streamable.com/74zeq9

**Comment by tonine-entro** [comment]
[NOT FIXED]
Tested with  [Shadow Word: Pain] doesn't dispell .

**Comment by Bart748** [comment]
updated ritualist dispell.
0 - none to 1 - magic
