### ISSUE TITLE
[NPC][Ability] Cabal Zealot - Enrage 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#442]
https://www.wowhead.com/npc=18638/cabal-zealot#abilities:mode=heroic

Missing Enrage.

**Comment by Bart748** [comment]
Cabal Zealot now casts Enrage at 25% HP and below

**Comment by MihawkEntropius** [comment]
https://streamable.com/njt6oe

**Comment by tonine-entro** [comment]
NPC not going to Enrage mode in both normal and heroic.
![image](https://user-images.githubusercontent.com/67378152/85895775-ed669080-b814-11ea-974a-b628cf9c1e46.png)

**Comment by Bart748** [comment]
Changed parameter 3 to force cast. Shape of Beast might fuck with Enrage though

**Comment by Nextcalibur** [comment]
Confirmed.
