### ISSUE TITLE
[NPC][Ability] Cabal Summoner - Shadow Bolt

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#444]
https://www.wowhead.com/npc=18632/cabal-executioner#abilities:mode=heroic

Not using shadow bolt. 

Edit: https://www.wowhead.com/npc=18634/cabal-summoner

**Comment by Bart748** [comment]
Wrong NPC linked

**Comment by Bart748** [comment]
NPC casts shadow bolt as event, now also as offense spell

**Comment by MihawkEntropius** [comment]
Working.
