### ISSUE TITLE
[NPC][Ability] Cabal Spellbinder - Shadow Bolt

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#445]
https://www.wowhead.com/npc=18639/cabal-spellbinder#abilities:mode=heroic

Not using Shadow bolt.

Note, when added check properly stay back and cast it and does not go in melee range asap.

**Comment by Bart748** [comment]
Shadow Bolt is part of an Event Script, Added Shadow Bolt to offensive spells

**Comment by MihawkEntropius** [comment]
Working.
