### ISSUE TITLE
[NPC][Ability] Nexus Terror - Shadows Embrace 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#447]
https://www.wowhead.com/npc=19307/nexus-terror#abilities:mode=heroic

Shadows Embrace missing.

**Comment by Bart748** [comment]
NPC should cast Shadow Embrace 3,6-16,9 seconds after entering combat, 15.7-24.1s repeating. Pleasse check this, it could be that other abilities are earlier, could force cast.

**Comment by MihawkEntropius** [comment]
I confirmed it works.
