### ISSUE TITLE
[Spell][Mage] Blizzard applying Winter's Chill stacks 

### ISSUE THREAD

**Issue by KroqGar** [Nextcalibur/Bugtracker#449]
Blizzard shoudn't apply Winter's Chill stacks prior 3.0.2.
 
WoWWiki edit from 2007-09-19 states: "Blizzard is the only frost spell that can not apply the winter's chill affect to the target."

Following Patch 3.0.2, the article (edited 2008-12-19) was updated to state "However, the fastest way to stack Winter's Chill on a target is by using the expensive Blizzard spell. ... Prior to Patch 3.0.2, Blizzard was the only frost spell that could not apply the Winter's Chill effect to the target."

Further edits on 2008-12-28 say "As of 3.0.2, Blizzard can apply the Winter's Chill effect where previously it did not. Each application is stacked per damage tick- with 8 ticks of damage per Blizzard, a single Blizzard is enough to apply all 5 applications by the 5th damage tick for the maximum critical strike bonus...In Patch 3.0.2, this debuff [Winter's Chill] was changed to increase all spells' critical strike chance (previously only Frost spells benefitted(sic) from it), a massive utility buff for Frost mages."

There are even forum posts on people curious why it doesn't stack in the Classic release of WoW.

**Comment by MihawkEntropius** [comment]
tested fixed
