### ISSUE TITLE
[NPC][Ability] Auchenai Soulpriest - Falter

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#450]
https://www.wowhead.com/npc=18493/auchenai-soulpriest#abilities

Not using Falter.

**Comment by Bart748** [comment]
NPC does cast Falter when the NPC reaches below 50% HP, every 20-30 seconds.

**Comment by tonine-entro** [comment]
NPC not casting falter even after hp below 50% both normal and heroic.

**Comment by Bart748** [comment]
changed event flag and action parameters. Should not force cast and interrupt previous cast)
