### ISSUE TITLE
[NPC][Mechanic] Cobalt Serpent - Moving into Melee

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#456]
https://www.wowhead.com/npc=19428/cobalt-serpent#abilities

He has ranged spell abilities and 1 to push back if someone comes into melee but he goes into melee first.

**Comment by Azelen** [comment]
https://youtu.be/a3sRBldPF64?t=195 at 3:20 he rushes into melee when engaged in combat.
