### ISSUE TITLE
Winterspring [NPC] [ABILITY]

### ISSUE THREAD

**Issue by Alucard-entropius** [Nextcalibur/Bugtracker#460]
Rogue thistle yeti missing Tendon rip ability
Ice Thistle Yeti doesnt use Tendon rip ability
https://classic.wowhead.com/spell=3604/tendon-rip
----------------------------------------------------------
Ragged Owlbeast not using its 2 abilites: Rend and Fastering Rash

https://classic.wowhead.com/spell=15848/festering-rash
----------------------------------------------------------
Mezzir the Howler doesnt use any of his 3 abilities
https://vanilla-twinhead.twinstar.cz/?npc=10197#abilities
----------------------------------------------------------
Rak'shiri doesnt use ability Terrify
https://vanilla-twinhead.twinstar.cz/?npc=10200#abilities
----------------------------------------------------------
Winterspring Screecher doesnt use ability Deafening Screech
https://classic.wowhead.com/spell=3589/deafening-screech
----------------------------------------------------------
Moontouched Owlbeast doesnt use its abilities: Moonfire and Rejuvination, also Moonfire is spamable when mob is MCed (no gcd)
https://vanilla-twinhead.twinstar.cz/?npc=7453#abilities
----------------------------------------------------------
Princess Tempestria needs 3 additional abilities besides Frostbolt + 4 bodyguard linked mobs, same as the mobs in the vicinity and set all 5 npcs to 2 days respawn
https://vanilla-twinhead.twinstar.cz/?npc=14457#abilities
----------------------------------------------------------

**Comment by Bart748** [comment]
Please add the NPC ids next time ^^ they are a bit more useful

**Comment by Alucard-entropius** [comment]
Right sorey, i knew i forgot something :/

**Comment by Bart748** [comment]
added abilities Tendon Rip (Spell=3604), Ice Blast (Spell=15878) to Rogue Ice Thistle (NPC=7457)
added abilities Tendon Rip (Spell=3604), Ice Blast (Spell=15878) to Ice Thistle (NPC=7458)
Added abilities Festering Rash (Spell=15848), Rend (Spell=13738) to Ragged Owlbeast (NPC=7450)
Added abilities Demoralizing Roar (Spell=15971), Frost Breath (Spell=3131), Terrifying Roar (Spell=14100) to Mezzir the Howler (NPC=10197)
Added abilities Enrage (15716) and Terrify (7399) to Rak'shiri (10200)
Added Ability Deafening Screech (3589) to Winterspring Screecher (7456)
Added Abilities Moonfire and Rejuvination to Moontouched Owlbeast
Added Abilites Cone of Cold, Frost Nova and Geyser (random) to Princess Tempestria and changed spawntime to 2 days
Added Ability Multishot to Bloodwarder Falconer

**Comment by tonine-entro** [comment]
[FIXED]

> added abilities Tendon Rip (Spell=3604), Ice Blast (Spell=15878) to Rogue Ice Thistle (NPC=7457) - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85892009-ce183500-b80d-11ea-8c5e-853031bf4d99.png)
![image](https://user-images.githubusercontent.com/67378152/85892025-d40e1600-b80d-11ea-9b5b-481df90cad6b.png)
> added abilities Tendon Rip (Spell=3604), Ice Blast (Spell=15878) to Ice Thistle (NPC=7458) - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85891542-e76cb180-b80c-11ea-9d7e-677af631f838.png)
> Added abilities Festering Rash (Spell=15848), Rend (Spell=13738) to Ragged Owlbeast (NPC=7450) - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85891733-43cfd100-b80d-11ea-8941-200cd962aa22.png)
> Added abilities Demoralizing Roar (Spell=15971), Frost Breath (Spell=3131), Terrifying Roar (Spell=14100) to Mezzir the Howler (NPC=10197) - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85892192-1b94a200-b80e-11ea-87f5-dc301ee150da.png)
![image](https://user-images.githubusercontent.com/67378152/85892259-36ffad00-b80e-11ea-851d-a97884925bfb.png)
![image](https://user-images.githubusercontent.com/67378152/85892292-4c74d700-b80e-11ea-914d-683aa1897c1d.png)
> Added abilities Enrage (15716) and Terrify (7399) to Rak'shiri (10200) - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85892347-68787880-b80e-11ea-8b13-f2eab520ff02.png)
![image](https://user-images.githubusercontent.com/67378152/85892417-82b25680-b80e-11ea-9d2c-f270917cd59f.png)
> Added Ability Deafening Screech (3589) to Winterspring Screecher (7456) - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85892563-ca38e280-b80e-11ea-8e7d-f227a63dca9a.png)
> Added Abilities Moonfire and Rejuvination to Moontouched Owlbeast - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85892633-e472c080-b80e-11ea-8fe6-7ebc062f921f.png)
![image](https://user-images.githubusercontent.com/67378152/85892651-f05e8280-b80e-11ea-9a9f-333ace2fb330.png)
> Added Abilites Cone of Cold, Frost Nova and Geyser (random) to Princess Tempestria and changed spawntime to 2 days - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85892812-3ca9c280-b80f-11ea-80ba-5a428e6b48f4.png)
![image](https://user-images.githubusercontent.com/67378152/85892827-43383a00-b80f-11ea-9386-879ff4c64d6f.png)
![image](https://user-images.githubusercontent.com/67378152/85892851-4cc1a200-b80f-11ea-976f-b11c796cb6e1.png)
![image](https://user-images.githubusercontent.com/67378152/85892894-64992600-b80f-11ea-8121-673b473845bb.png)
> Added Ability Multishot to Bloodwarder Falconer - **Fixed**
![image](https://user-images.githubusercontent.com/67378152/85893155-f012b700-b80f-11ea-9273-dd3b3373e62b.png)
