### ISSUE TITLE
[NPC][Raid][Ability]Hellfire Warder - Fear

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#461]
https://wow.gamepedia.com/Hellfire_Warder

In magtheridon's lair, they should use fear as mentioned above. 

Its missing on wowhead but it was mentioned there in comments " I was feared endlessly around the northern part of the raid instance"

https://www.wowhead.com/npc=18829/hellfire-warder#comments

**Comment by Bart748** [comment]
Ability Fear (Spell=?) not found in any of the databases.
Abilities found for Hellfire Warder (NPC=18829):
Death Coil (Spell=34437) (Implemented)
Rain of Fire (Spell=34435) (Implemented)
Shadow Bolt Volley (Spell=39175) (Implemented)
Shadow Burst (Spell=34436) (Implemented)
Shadow Word: Pain (Spell=34441) (Implemented)
Unstable Affliction (Spell=34439) (Implemented)

NPC use Death Coil to fear people "endlessly around the northern part of the raid instance"
