### ISSUE TITLE
[NPC][Raid][Ability] Bloodwarder Marshal - Bloodthirst

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#462]
https://www.wowhead.com/npc=20035/bloodwarder-marshal#abilities

Not using bloodthirst ability.

**Comment by Bart748** [comment]
Bloodwarder Marshal (NPC=20035) uses Bloodthirst (Spell=35949) at 50% HP.

**Comment by tonine-entro** [comment]
[FIXED]
NPC is casting the spell at 50% HP.
![image](https://user-images.githubusercontent.com/67378152/85773714-c5572e80-b73b-11ea-8efc-99af5f1a24bf.png)
