### ISSUE TITLE
[NPC][Ability][Raid] Tempest Falconer - Immolation Arrow

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#465]
https://www.wowhead.com/npc=20037/tempest-falconer#abilities

Missing Immolation Arrow ( and immolation if not same spell)

Was report in below report but making a separate one. 

https://github.com/Nextcalibur/Bugtracker/issues/329

**Comment by Azelen** [comment]
They use it, just not on their primary target and it has a long cooldown (18-28s).
