### ISSUE TITLE
Desolace zone [NPC][ABILITY]

### ISSUE THREAD

**Issue by Alucard-entropius** [Nextcalibur/Bugtracker#469]
---Gritjaw Basilisk (Entry: 4728) and Hulking Gritjaw Basilisk (Entry: 4729) not using ability Crystaline Slumber (https://classic.wowhead.com/spell=3636/crystalline-slumber)

---Hatefury Shadowstalker (Entry: 4674) not using gouge ability (https://vanilla-twinhead.twinstar.cz/?npc=4674#abilities)

---Kolkar Windchaser (Entry: 4635) doesnt use ability Enveloping winds (https://vanilla-twinhead.twinstar.cz/?npc=4635#abilities)

---Khan Jehn (Entry: 5601) doesnt use ability Sunder Armor(https://vanilla-twinhead.twinstar.cz/?npc=5601#abilities)

---Nether Sorceress (Entry: 4684) not using Frost Nova (https://vanilla-twinhead.twinstar.cz/?spell=11831) ability 99% of the time, uses it only after Enslave demons runs out and as an opener.

---Doomwarder Captain (Entry: 4680) doesnt use Battle shout ability (https://vanilla-twinhead.twinstar.cz/?spell=9128)

---This needs linking, to start and stop at same time (https://i.imgur.com/JEc324G.jpg)
Selected: [Cork Gizelton] -SpawnId: 28714 Entry: 11625 First in caravan line
Selected: [Gizelton Caravan Kodo] -SpawnId: 27290 Entry: 11564 seconf in caravan line
Selected: [Rigger Gizelton]-SpawnId: 28728 Entry: 11626 third in caravan line
[Gizelton Caravan Kodo]-SpawnId: 27289 Entry: 11564 fourth in caran line
Bug refferenced in #31 Escort quest

---Slitherblade Oracle (Entry: 4718) doesnt use ability Slow (https://vanilla-twinhead.twinstar.cz/?npc=4718#abilities)

---Heretic Crystal Guard (Entry: 26166) missing all abilities (https://www.wowhead.com/npc=26166/heretic-crystal-guard#abilities)(SPAWNED BY MIDSUMMER FELSTIVAL!!!)

---Burning Blade Adept (Entry: 4665) not using its Bloodlust (https://vanilla-twinhead.twinstar.cz/?spell=6742) ability correctly. What should happen is that he casts it on allies in battle, what currently happens is that he casts it on himself near death ("...runs away in fear" + cast)

**Comment by Bart748** [comment]
Gritjaw Basilisk and Hulking Basilisk have a 75% to cast Crystaline Slumber on a random target except tank INSIDE dungeon only.
Added ability Gouge to Hetefury Shadowstalker
Updated Sunder armor event_script for Khan Jehn. Should be doing it on combat now.
Nether Sorceress should cast frost nova when the range is between 0-8 yards, every 22-25 seconds, 85% chance.
Updated Eventflag for Battle shout for Doomwarder Captain (only dungeons to always)
Updated Eventflag for Slow for Slitherblade oracle (only dungeons to always)
Added abilities Hamstring, Localized Toxin, Rend and Slitherstrike to Heretic Crystal Guard:
Rend: on combat, repeat 45-60s
hamstring: when TARGET is below 30% hp, every 30 seconds
Localized Toxing:  on combat, 15s, 30s repeat (75% chance)
Slitherstrike: on combat, 1,5s, 5s repeat (75% chance)

Burning Blade Adept works correctly. Bloodlust at 40%, Flee at 15%

No changes to the Caravan, needs to be made into formation and readd 281 waypoints, maybe make this a seperate issue.

**Comment by Nextcalibur** [comment]
Caravan event is duplicate issue of https://github.com/Nextcalibur/Bugtracker/issues/32

Needs a complete remake of waypoints and proper AI Scripts. will take some time to fix this.
