### ISSUE TITLE
[NPC][Ability][Raid] Underbog Colossus - Acid Geyser

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#470]
https://www.wowhead.com/npc=21251/underbog-colossus#comments

Acid Geyser and Parasites:
Folks in melee will get a debuff that ticks for ~2k for a few seconds, then a Serpentshrine Parasite will spawn from them (they have 1hp, thunderclap kills them). Rogues can cloak of shadows the infection off.

https://wowwiki.fandom.com/wiki/Underbog_Colossus

Acid Geyser - Does ~2k nature damage per tick over around 10 seconds in a frontal cone to a random player in range.

There's 3 types of Colossus, this is the type "B" on wowwiki. 

The ticks should be ~2k  but instead they are 1450-1550 (not counting resists)

Underbog Colossus's Acid Spray hits Testodruid for 1452 Nature.
Underbog Colossus's Acid Spray hits Testodruid for 1492 Nature.
Underbog Colossus's Acid Spray hits Testodruid for 1498 Nature.
Underbog Colossus's Acid Spray hits Testodruid for 1555 Nature.
Underbog Colossus's Acid Spray hits Testodruid for 1434 Nature.
Underbog Colossus's Acid Spray hits Testodruid for 1443 Nature.
Underbog Colossus's Acid Spray hits Testodruid for 1559 Nature.
Underbog Colossus's Acid Spray hits Testodruid for 1529 Nature.

**Comment by Azelen** [comment]
Acid Geyser (Acid Spray) damage comes from client files.

![зображення](https://user-images.githubusercontent.com/667107/116760477-ab524080-aa1d-11eb-86df-33d0fb67527e.png)
