### ISSUE TITLE
[NPC][Raid][Ability] Underbog Colossus - Spore Quake

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#473]
Spore Quake - Does ~2k nature damage per tick along with knockdowns over ~12 seconds to everyone within 30 yards. Melee should run out for this (they shouldn't take more then a tick or two of it as long as they don't get knocked down).

Its dealing 1.3k - 1.5k damage right now. 

Underbog Colossus's Spore Quake Effect hits Testodruid for 1444 Nature.
Underbog Colossus's Spore Quake Effect hits Testodruid for 1461 Nature.
Underbog Colossus's Spore Quake Effect hits Testodruid for 1493 Nature.
Underbog Colossus's Spore Quake Effect hits Testodruid for 1422 Nature.
Underbog Colossus's Spore Quake Effect hits Testodruid for 1402 Nature.
Underbog Colossus's Spore Quake Effect hits Testodruid for 1312 Nature.

**Comment by Azelen** [comment]
Spell damage comes from client files.

![зображення](https://user-images.githubusercontent.com/667107/116759741-c3c15b80-aa1b-11eb-9505-24856f79b37c.png)
