### ISSUE TITLE
[Raid][NPC][Ability] Greyheart Tidecaller - Chain Lightning

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#474]
https://wowwiki.fandom.com/wiki/Greyheart_Tidecaller

They have a chain lightning which silences everyone it hits but doesn't hit particularly hard.

https://www.wowhead.com/npc=21229/greyheart-tidecaller#comments

Wowhead does not list the ability but its mentioned in comments: They have a chain lightning which silences everyone it hits but doesn't hit particularly hard.

**Comment by Azelen** [comment]
There's only one spell that fits this description and it's https://tbcdb.com/?spell=38634. It's used by Greyheart Nether-Mages, not Tidecallers.
