### ISSUE TITLE
[NPC] [Teldrassil] Giant Webwood Spider isn't using its abilities

### ISSUE THREAD

**Issue by tonine-entro** [Nextcalibur/Bugtracker#478]
Giant Webwood Spider not using its abilities. Only Tbc db has list of its abilities other websites don't.

https://wowwiki.fandom.com/wiki/Giant_Webwood_Spider
https://classic.wowhead.com/npc=2001/giant-webwood-spider
https://tbcdb.com/?npc=2001#abilities

Selected: [Giant Webwood Spider]
[14:23:22]SpawnId: 47621 Entry: 2001
[14:23:22]DisplayId: 6808 (Native: 6808).

**Comment by Nextcalibur** [comment]
Fixed next restart.
