### ISSUE TITLE
[NPC] [Azuremyst Isle] Tolaan not giving the quest.

### ISSUE THREAD

**Issue by tonine-entro** [Nextcalibur/Bugtracker#479]
NPC Tolaan doesn't give any quest.
https://wowwiki.fandom.com/wiki/Tolaan
https://tbcdb.com/?npc=16546#starts
https://de.wowhead.com/npc=16546/tolaan#starts

Selected: [Tolaan]
[14:51:21]SpawnId: 57475 Entry: 16546
[14:51:21]DisplayId: 16253 (Native: 16253).

**Comment by MihawkEntropius** [comment]
https://www.wowhead.com/quest=9309/the-missing-scout

Did you take the pre quest?
