### ISSUE TITLE
[NPC] [ Azuremyst Isle ] NPC reactions

### ISSUE THREAD

**Issue by tonine-entro** [Nextcalibur/Bugtracker#480]
Mutated Root Lasher should be hostile
Selected: [Mutated Root Lasher]
[14:55:58]SpawnId: 57300 Entry: 16517
[14:55:58]DisplayId: 19455 (Native: 19455).
https://tbcdb.com/?npc=16517
https://wow.gamepedia.com/Mutated_Root_Lasher

Surveyor Candress should be hostile
https://tbcdb.com/?npc=16522#abilities
https://wowwiki.fandom.com/wiki/Surveyor_Candress
https://wow.gamepedia.com/Surveyor_Candress
https://www.wowhead.com/npc=16522/surveyor-candress
Selected: [Surveyor Candress]
[14:57:50]SpawnId: 57439 Entry: 16522
[14:57:50]DisplayId: 16249 (Native: 16249).

**Comment by Nextcalibur** [comment]
Fixed.
