### ISSUE TITLE
[NPC] [Nagrand] NPC issues

### ISSUE THREAD

**Issue by tonine-entro** [Nextcalibur/Bugtracker#485]
> [Boulderfist Warrior] doesn't use shoulder charge
[23:47:49]SpawnId: 60102 Entry: 17136
[23:47:49]DisplayId: 18356 (Native: 18356).
https://tbcdb.com/?npc=17136#abilities
https://www.wowhead.com/npc=17136/boulderfist-warrior#comments

> [Boulderfist Mage] doesn't use bloodlust(on low health) and fire blast
[23:52:01]SpawnId: 60124 Entry: 17137
[23:52:01]DisplayId: 18333 (Native: 18333).
https://www.wowhead.com/npc=17137/boulderfist-mage#abilities doesn't say it uses fire blast
https://tbcdb.com/?npc=17137#abilities

> [Zorbo the Advisor] not casting any abilities
[00:03:00]SpawnId: 65805 Entry: 18413
[00:03:00]DisplayId: 11550 (Native: 11550).
https://www.wowhead.com/npc=18413/zorbo-the-advisor#abilities
https://tbcdb.com/?npc=18413#abilities

**Comment by Bart748** [comment]
Added Ability Shoulder charge to Boulderfist Warrior
Added ability Bloodlust to bolderfist mage @30%hp, updated fireblast to force cast
Added Abilities Frost Shock, Healing Wave, Scorching Totem to Zorbo the Advisor
Frost shock on distance 5-20 yards
Healing wave at 75-0% hp, 75% chance
Totem in combat every 45-60s
