### ISSUE TITLE
[NPC][Ability] Elwynn Forest 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#489]
https://classic.wowhead.com/npc=61/thuros-lightfingers#abilities as well as some other npc  Missing backstab 
https://tbcdb.com/?npc=61
https://tbcdb.com/?npc=99#abilities
https://tbcdb.com/?npc=473#abilities
Probably this ability https://tbcdb.com/?spell=53#see-also-ability 

https://classic.wowhead.com/npc=103/garrick-padfoot#abilities supposed to be red npc name and not yellow to alliance.

**Comment by Nextcalibur** [comment]
Thuros Lightfingers fixed.

**Comment by Nextcalibur** [comment]
Garrick Padfoot fixed.

**Comment by Nextcalibur** [comment]
Morgaine the Sly fixed.

**Comment by Nextcalibur** [comment]
Morgan the Collector working.
