### ISSUE TITLE
[NPC][Ability][Mechanic] Durotar

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#490]
https://classic.wowhead.com/npc=3101/vile-familiar#abilities  They move into melee even if having plenty of mana. 

https://tbcdb.com/?npc=3105#abilities  Claw Grasp missing.

https://classic.wowhead.com/npc=3183/yarrog-baneshadow#abilities  should be hostile, its neutral right now by default. 

https://tbcdb.com/?npc=3226#abilities  missing poison.

**Comment by Nextcalibur** [comment]
Fixed Vile Familiar ranged combat.

**Comment by Nextcalibur** [comment]
Makrura Snapclaw already has ability.

**Comment by Nextcalibur** [comment]
Fixed Yarrog Baneshadow.

**Comment by Nextcalibur** [comment]
Corrupted Scorpid
