### ISSUE TITLE
[Quest reward] Torch tossing

### ISSUE THREAD

**Issue by Synful-Syn** [Nextcalibur/Bugtracker#505]
The quest "Torch tossing" gives way too much gold.

The amount of gold shown on wowhead is way below what we're seeing on the server.

https://www.wowhead.com/quest=11922/torch-tossing

(In the images, I show my level and the gold rewards in the images)
At level 15, it should give 7s.
![image](https://user-images.githubusercontent.com/22718174/86426196-0bb90a00-bcb5-11ea-8313-22b1486cf36f.png)

At level 70, it should give 4g40s.
![image](https://user-images.githubusercontent.com/22718174/86426211-14114500-bcb5-11ea-963f-603e062347be.png)

**Comment by Nextcalibur** [comment]
Nice find, will fix :)

**Comment by Nextcalibur** [comment]
Fixed !
