### ISSUE TITLE
[NPC] [Bloodmyst Isle] Ability issues

### ISSUE THREAD

**Issue by tonine-entro** [Nextcalibur/Bugtracker#508]
>  [Axxarien Shadowstalker] casts [Corruption]. It has no abilities.
[21:46:19]SpawnId: 62410 Entry: 17340
[21:46:19]DisplayId: 2011 (Native: 2011).
https://www.wowhead.com/npc=17340/axxarien-shadowstalker
https://tbcdb.com/?npc=17340

> [Axxarien Trickster] uses Eviscerate. Should not use any abilities.
[21:49:15]SpawnId: 62424 Entry: 17341
[21:49:15]DisplayId: 2014 (Native: 2014).
https://tbcdb.com/?npc=17341
https://www.wowhead.com/npc=17341/axxarien-trickster

**Comment by Bart748** [comment]
Not all NPCs in the game have abilities. Some mobs are considered "Dumb" mobs, they just melee attack
