### ISSUE TITLE
[NPC][Open world] Fel Reaver

### ISSUE THREAD

**Issue by Synful-Syn** [Nextcalibur/Bugtracker#509]
2 issues noted about him...

The Fel Reaver does not use his ability War Stomp.

NPC: https://www.wowhead.com/npc=18733/fel-reaver
War Stomp: https://www.wowhead.com/spell=41534/war-stomp

According to his wowhead screenshots, the Fel Reaver should also wander into the Pools of Aggonar and Fallen Sky Ridge, however, I don't know the exact path. :)
He currently only wander...
North of the crashed zepplin
South of Honor Hold
North east of Zeth'Gor
Path of Anguish
North east of Honor Hold
Path of Glory
East of Thrallmar
Northern part of The Legion Front

**Comment by Megalomaniac6** [comment]
Added spell "War stomp" to Fel Reaver.
Verifying the waypoints and fixing them at a later point.

**Comment by Synful-Syn** [comment]
I just wandered in Hellfire and then I found out that there is currently 2 Fel Reavers and they both have their own path. They never meet each other. I don't know if we're only supposed to have a single Fel Reaver having both paths or 2 Fel Reavers with their individual paths.

**Comment by Megalomaniac6** [comment]
There is supposed to be 2 Fel Reavers and their pathing looks alright good. Closing the issue.
