### ISSUE TITLE
[NPC][REACT] Neutral npc that should be Enemies

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#514]
https://tbcdb.com/?npc=15273

https://tbcdb.com/?npc=15298

https://tbcdb.com/?npc=15367

https://tbcdb.com/?npc=1667

https://tbcdb.com/?npc=1506

https://tbcdb.com/?npc=1507

https://tbcdb.com/?npc=946

https://tbcdb.com/?npc=2966

https://tbcdb.com/?npc=16517

**Comment by Nextcalibur** [comment]
Fixed.
