### ISSUE TITLE
[NPC][Ability] Tirisfal Glades

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#515]
https://classic.wowhead.com/npc=1664/captain-vachon#abilities
Missing Shield bash  https://tbcdb.com/?spell=11972 timer is from what I could see roughly 25-30 second CD on it. 

https://tbcdb.com/?npc=1505
it should be red and not neutral. https://tbcdb.com/?npc=1505

https://classic.wowhead.com/npc=1688/night-web-matriarch
should be red https://tbcdb.com/?npc=1688

https://classic.wowhead.com/npc=4284/scarlet-augur#abilities
https://tbcdb.com/?spell=1490  Missing.

https://classic.wowhead.com/npc=4282/scarlet-magician#abilities
https://tbcdb.com/?spell=8457 Missing

**Comment by Nextcalibur** [comment]
Captain Vachons shield bash is only cast as an intterupt. Wont use it unless you are casting a spell.

**Comment by Nextcalibur** [comment]
All fixed next restart.
