### ISSUE TITLE
[NPC][Ability] Silverpine Forest

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#516]
https://classic.wowhead.com/npc=1893/moonrage-sentry#abilities / https://wowwiki.fandom.com/wiki/Moonrage_Sentry
https://classic.wowhead.com/spell=71/defensive-stance  I am going to assume its this one, I could not find any evidence on other data bases, like tbcdb.com etc. they dont show def stance there. 

https://classic.wowhead.com/npc=1940/rot-hide-plague-weaver#abilities
https://tbcdb.com/?spell=3256

https://classic.wowhead.com/npc=2054/sickly-refugee#abilities
https://tbc-twinhead.twinstar.cz/?spell=1776   http://wotlk.cavernoftime.com/spell=2589  (best I could find for backstab was from a wotlk DB)

**Comment by Nextcalibur** [comment]
Duplicate? Fixed.
