### ISSUE TITLE
[NPC][Ability] Azshara

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#517]
https://classic.wowhead.com/npc=6116/highborne-apparition#abilities
https://vanilla-twinhead.twinstar.cz/?spell=12542

https://classic.wowhead.com/npc=6201/legashi-rogue#abilities
https://vanilla-twinhead.twinstar.cz/?spell=19448

https://classic.wowhead.com/npc=6372/makrinni-snapclaw#abilities
Not an ability bug.... these NPC are level 8-9 instead of 50-51

https://classic.wowhead.com/npc=8764/mistwing-ravager#abilities
https://tbcdb.com/?spell=8806  - if he is supposed to do it from a distance (as its called a shot) he goes directly into melee. 

https://classic.wowhead.com/npc=7886/spitelash-enchantress#abilities
https://tbcdb.com/?npc=7886#abilities  both abilities missing

https://classic.wowhead.com/npc=6195/spitelash-siren#abilities:0+1+17+2
I think this one has some scripting issue, it has "shoot" "frost shot" etc. but instead of shooting from far away it goes into melee.

**Comment by Bart748** [comment]
6116: Cant add spells, Need more information about correct spells.
6201: Cant add spells, Need more information about correct spells
Makrinni Snapclaw: changed level from 8-9 to 50-51
Mistwing Ravager: changed Cast flag to ranged
Spitelash Enchantress: added Enchanted Quickness and Frost shock
Spitelash Siren: Added Frost Shot, Frost Nova, renew and shoot
