### ISSUE TITLE
[Ability][NPC] Tanaris

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#518]
https://classic.wowhead.com/npc=8667/gusting-vortex#abilities
https://vanilla-twinhead.twinstar.cz/?spell=6982

https://classic.wowhead.com/npc=5618/wastewander-bandit#abilities
https://tbcdb.com/?spell=8629

**Comment by Bart748** [comment]
8667 should cast Gust of Wind: 100%, 8.5s-24.8s, repeat: 20.5s-40.2s, random hostile
Wastewander Bandit: added Backstab and Gouge
