### ISSUE TITLE
[NPC] Ewe

### ISSUE THREAD

**Issue by Synful-Syn** [Nextcalibur/Bugtracker#522]
There's one too many Ewe. :)

https://www.wowhead.com/npc=19665/ewe#comments:id=880466

**Comment by MihawkEntropius** [comment]
By PAWilds (5,642 – 1·13·25) on 2011/11/19 (Patch 4.2.2)

The achievement Ewe can be found in Shattrath, under the north bridge and next to Farmer Griffith / http://www.wowhead.com/npc=20123.

I found 2 Ewe in game, should there be less?

**Comment by Synful-Syn** [comment]
![image](https://user-images.githubusercontent.com/22718174/86657967-ac117600-bfb6-11ea-89fe-46b24c156386.png)
There should be only one. :)
https://www.wowhead.com/npc=19665/ewe#comments:id=880466

**Comment by Synful-Syn** [comment]
Nevermind, Wowhead comments are incoherent.
![image](https://user-images.githubusercontent.com/22718174/86658799-55586c00-bfb7-11ea-8392-b2bec162eda6.png)
https://www.wowhead.com/npc=20123/farmer-griffith#comments:id=38947
