### ISSUE TITLE
[NPC][Ability] Feralas 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#524]
https://classic.wowhead.com/npc=5236/gordunni-shaman#abilities
No other database mention fire nova totem, they are level 44-45 and this ability is for 42+, I assume its that one.
https://classic.wowhead.com/spell=11314/fire-nova-totem

https://classic.wowhead.com/npc=7725/grimtotem-raider#abilities
https://vanilla-twinhead.twinstar.cz/?spell=11314  - This also confirms the above suggestion for rank 4 fire nova totem.

https://classic.wowhead.com/npc=7727/grimtotem-shaman#abilities:50+1+17+2
https://vanilla-twinhead.twinstar.cz/?spell=5532

https://classic.wowhead.com/npc=5320/jademir-boughguard#abilities:0+1+17+2
https://classic.wowhead.com/spell=12021/fixate   I dont quite understand this spell but it didnt seem to be done on any of my 2 characters attacking it. Its not really important to fix it, its a 60 elite for the world boss from corrupted green dragon flight. 

https://classic.wowhead.com/npc=5286/longtooth-runner#abilities
https://classic.wowhead.com/spell=3149/furious-howl

https://classic.wowhead.com/npc=5255/woodpaw-reaver#abilities
https://tbcdb.com/?spell=20605

https://classic.wowhead.com/npc=5354/gnarl-leafbrother#abilities
https://streamable.com/hf8pi2  I found no evidence he should run that fast lol

**Comment by Bart748** [comment]
Gordunni Shaman: Fire Nova Totem Added
Grimtotem Raider.....?
Grimtotem Shaman: Fire Nova Totem Added
Fixate... I have no idea? I would say amazing tank spell... but besides that useless?
Furious Growl is a hunter pet spell
Woodpaw Reaver updated cleave ability
Changed movement speed of Gnarl Leafbrother

**Comment by MihawkEntropius** [comment]
Update:

[23:25:44]Selected: [Grimtotem Naturalist]
[23:25:44]SpawnId: 50037 Entry: 7726

https://classic.wowhead.com/npc=7726/grimtotem-naturalist#abilities

They should have a 50:50 chance to be in bear form, half of them should be in bear form by default before combat and other half should be in human (tauren) form and cast wrath instead.
