### ISSUE TITLE
[NPC][Ability] Dustwallow Marsh

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#526]
https://wow.gamepedia.com/Coral_Shark
Completely missing from the game,  https://classic.wowhead.com/npc=5434/coral-shark#abilities

https://wow.gamepedia.com/Corrosive_Swamp_Ooze / https://classic.wowhead.com/npc=4392/corrosive-swamp-ooze#abilities
Missing from the game.

https://classic.wowhead.com/npc=4412/darkfang-creeper#abilities
https://classic.wowhead.com/spell=744/poison

https://classic.wowhead.com/npc=4403/muckshell-pincer#abilities
https://classic.wowhead.com/spell=12787/thrash  - I just took one of the "trash" at random, they basically have same effect and level requirement. 

https://classic.wowhead.com/npc=4402/muckshell-snapclaw#abilities
Missing from the game? https://wow.gamepedia.com/Muckshell_Snapclaw  it was not removed until Cata.

https://wow.gamepedia.com/Withervine_Bark_Ripper / https://classic.wowhead.com/npc=4386/withervine-bark-ripper#abilities 
Missing from the game?

**Comment by Bart748** [comment]
Added 63 Corrosive Swp Ooze to Dustwallow Marsh
4412: Slowing Poison: 85%, start of combat 5-15s, repeat 12-15s, random target
Muckshell Pincer: added Trash
Added 38 Muckshell Snapclaw to Dustwallow Marsh
Muckshell Snapclaw: Added Poison
Added 11 Withervine Bark Ripper to Dustwallow Marsh
Withervine Bark Ripper: added Pierce Armor
