### ISSUE TITLE
[NPC][Ability] Comsume Flesh hurts the victim but also heals the victim

### ISSUE THREAD

**Issue by Synful-Syn** [Nextcalibur/Bugtracker#532]
The skill Comsume Flesh hurts the victim but also heals the victim with the same amount.

![WoWScrnShot_070720_192920](https://user-images.githubusercontent.com/22718174/86856106-a042b400-c089-11ea-8901-0895f058d3cf.jpg)

Consume Flest: https://www.wowhead.com/spell=37933/consume-flesh
Used by Ravenous Flayer: https://www.wowhead.com/npc=21196/ravenous-flayer

Edit: I do not know if they should stop using their Consume Flesh if you were to move away.

**Comment by MihawkEntropius** [comment]
tested working
