### ISSUE TITLE
[hunter][skill] Auto Shot

### ISSUE THREAD

**Issue by weldim** [Nextcalibur/Bugtracker#544]
Auto Shot seems to randomly stop working until you kill the mob when the mob is within Auto Shot range.  When this happens I am unable to Auto Shot or use any ranged abilities.  I have seen this happen on other private servers and in those situations feign death would usually fix it, unfortunately I am not high enough to test with feign.

I have experienced this ~4-5 times between levels 1-8

**Comment by MihawkEntropius** [comment]
After having tested this bug I made this observations:

1. It is replicable, it bugs when "auto shot" ability is spammed fast 
2. when bugged the auto shot ability does not react (it does not activate auto shot)
3. Moving character does not allow to reactivate auto shot
4. moving into melee range and melee hitting does not unbug auto shot
5. Using raptor Strike unbugs auto shot
6. Using right click to auto attack even if spammed wont bug auto shot. 
7. right click does not unbug auto shot.

**Comment by MihawkEntropius** [comment]
tested working
