### ISSUE TITLE
[NPC][Behavior] Doc MixilPixil 

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#551]
https://streamable.com/53n386

Just a weird behavior of NPC after a player delivered his quest to him.

**Comment by Synful-Syn** [comment]
NPC: https://classic.wowhead.com/npc=7207/doc-mixilpixil

I don't know which one of these 3 quests it was.
https://classic.wowhead.com/quest=2607/the-touch-of-zanzil
https://classic.wowhead.com/quest=2608/the-touch-of-zanzil
https://classic.wowhead.com/quest=2609/the-touch-of-zanzil

**Comment by MihawkEntropius** [comment]
There was weird reaction of the npc once where the npc was moving around weirdly , could not reproduce it again with any of the above quests, closing.
