### ISSUE TITLE
Warp Stalker

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#56]
About this, checked the abilities of the npc, it does not show that charge ability to appear behind the target, could have been changed but it does it on Exc

I am going to properly explain this and it wont require any screen shot

Now on the topic : 

https://www.wowhead.com/npc=18464/warp-stalker#abilities

When I attack them, they come closer to me, blink behind my back at a range that is not close enough to melee attack me. 

They continuously throw slow on me (npc ability) but they are not melee hitting me nor are they moving/getting closer to me to attack me, fact is unless I move away/closer to them they are in a bugger immobile state.

**Comment by Alucard-entropius** [comment]
Slow ability is working imo, as its 10 sec cd ability with 10 sec duration
