### ISSUE TITLE
[NPC][Ability] Durnholde Rifleman - Scatter Shot

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#563]
https://www.wowhead.com/npc=17820/durnholde-rifleman#abilities

https://www.wowhead.com/spell=115199/scatter-shot

The issue with this is that the scatter shot is not randomized to party members and always goes to the party member that has agroo on the Rifleman.

**Comment by Nextcalibur** [comment]
Working as intended.
