### ISSUE TITLE
[NPC] [ShadowMoon Valley] Shadowmoon Zealot ignores pet

### ISSUE THREAD

**Issue by tonine-entro** [Nextcalibur/Bugtracker#565]
Shadowmoon Zealot is ignoring the pets, so that you can't tank them with it.
Seems that the pets don't get the effect of Spectrecles

Quest - https://tbc-twinhead.twinstar.cz/?quest=10625

Item - https://www.wowhead.com/item=30719/spectrecles

Ghosts(Shadowmoon Zealot) are only visible when using the item **Spectrecles**.

**Comment by Nextcalibur** [comment]
Can you confirm that spectrecles should apply to pets?

**Comment by Olion17** [comment]
https://www.wowhead.com/quest=10625/spectrecles#comments
In summary:

> (Patch 2.4.1) As of this writing, May 15, 2008, this quest is bugged for Hunters. When you send your pet in to fight, it will attack once and then stop. I contacted a GM and he said it's a known issue that will be addressed in a future update.
> (Patch 3.0.2) As of the Wrath of the Lich king patch that changed talent points this quest has been fixed. As a BM hunter my pet fights these guys no different than any other mob.

In between, the Spectrecles spells are fully identical in TBC and WotLK Spell.dbc. Either some server-side ones were added, or it had been implemented by a separate core mechanic.
