### ISSUE TITLE
Quest "The Fel and the Furious" is not completable within time limit

### ISSUE THREAD

**Issue by Delinquence** [Nextcalibur/Bugtracker#568]
In this quest you're supposed to control a fel reaver, but half of it's abilities are not working, so you can only use 2 spells that have too long of a cooldown to kill the 60 infernals. Besides that the infernals are non targetable, so you cannot use the fel reavers basic attack to kill them.

**Comment by MihawkEntropius** [comment]
https://github.com/Nextcalibur/Bugtracker/issues/17

**Comment by Nextcalibur** [comment]
Duplicate of #17
