### ISSUE TITLE
Dark Portal - Path of Glory

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#57]
This report is about the demons fighting in front of the dark portal in outland to be short, I think its an interesting part of the expansion and first impression that matter when you enter in outland.

I understand it is EXTREMELY hard to script this event, where monsters spawn and walk to it, but they way it is currently set up is that all the guards on the stairs are all over the place ( which is easy to fix, just move them) and there are NO ATTACKS what so ever there. I highly suggest you atleast make the demons spawn at the front and fight, not just walking around.

 

also if you do engage combat with the pit commander, he doesnt cast rain of fire or cleave, just auto attacks. AND i am horde, and i can attack justinius the harbinger as if he is just a normal yellow mob.

**Comment by Nextcalibur** [comment]
Scripted :)
