### ISSUE TITLE
[Quest][Object] Digging Up the Past - Charred Bone Fragment

### ISSUE THREAD

**Issue by Scalebeard** [Nextcalibur/Bugtracker#571]
**Expected behavior**

The Charred Bone Fragment (Object ID 181963) that needs to be looted for Digging Up the Past (Quest ID 9680). The object requires 15 minutes to respawn, which is intended.

**Requested behavior**

Requesting to change the respawn timer of the object to 1 minute, as a QoL feature.

**Comment by MihawkEntropius** [comment]
tested working
