### ISSUE TITLE
Fate of Kagrosh

### ISSUE THREAD

**Issue by simonred** [Nextcalibur/Bugtracker#578]
You should interact with Kagrosh and get access to his backpack. 

When interacting with him. nothing happens when you click to check the backpack.

**Comment by tonine-entro** [comment]
Tested in both PTR and Live. Interacting with the NPC doesn't give item - [Kagrosh's Pack
](https://www.wowhead.com/item=30659/kagroshs-pack)

[**NPC Info**](https://wow.gamepedia.com/Kagrosh)
Selected: [Kagrosh]
[00:25:52]SpawnId: 86870 Entry: 21725
[00:25:52]DisplayId: 20304 (Native: 20304).

**Comment by tonine-entro** [comment]
Just tested in it and was able to complete the quest. Working as intended.

**Comment by tonine-entro** [comment]
![WoWScrnShot_072620_231824](https://user-images.githubusercontent.com/67378152/88485823-a3e59e80-cf96-11ea-8de0-40c5005d1ba7.jpg)
