### ISSUE TITLE
[Skill][Fishing] No way to be late to hook fish

### ISSUE THREAD

**Issue by Olion17** [Nextcalibur/Bugtracker#580]
What should happen: if you fail to click the fishing bobber in time, the spellcast channel breaks and you get an error message like "You got no fish".

What happens actually: the channel continues, you are free to click the bobber anytime since its signal up to the channel timeout, catching a fish still. The longest proven delay is 9-10 secs.

Hint: handling GO Fishing bobber in, iirc, Gameobject::Update.

**Comment by MihawkEntropius** [comment]
To clarify, there seems to be unlimited (until the channeling stop) time to click on the fishing float if the fishing skill is high enough above the required skill to fish in that zone. 

It is not clear to me at which skill difference this behavior start but it seems that if the fish is not in the yellow skill zone, 1-2~ seconds to react then clicking can wait as long as the channeling is still active after the fish pulled the float down.

If the zone you are fishing in is not easy for your skill level you still need to be quick.

**Comment by MihawkEntropius** [comment]
tested working
