### ISSUE TITLE
[Mage Quest] Control

### ISSUE THREAD

**Issue by Synful-Syn** [Nextcalibur/Bugtracker#582]
The objective of the quest is to kill a Quel'dorei Magewraith.

![](https://media.discordapp.net/attachments/688094148703944721/735873650561122373/unknown.png)
![image](https://media.discordapp.net/attachments/688094148703944721/735873704042430484/unknown.png)

However, it seems to have a hidden objective to complete. Alucard asked if I got stunned and I didn't get stunned while I did it.
![image](https://user-images.githubusercontent.com/22718174/88433029-52d57f00-cdcb-11ea-908f-6fd7f25bf774.png)

After trying again, I decided to try to get stunned and it happens upon the Magewraith's death (I've meleed it. Was I previously out of range? Did I resist the stun? I have no idea).
Getting stunned could be one of the triggers that allows handing-in.

Quest: https://www.wowhead.com/quest=9595/control

**Comment by Alucard-entropius** [comment]
I will close this for now as its doable, but **bad wording by Blizzard quest writers**. _"Stun"_ has a chance of happening. For every next mage having the issue, refer him to this report or to me.

Alucard.
