### ISSUE TITLE
[NPC][Karazhan] Spectral Servant 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#584]
https://www.wowhead.com/npc=16407/spectral-servant#comments

This NPC in Karazhan was hitting me for 2.5-3k , perhaps some hits even higher, I only checked my death log.

I have 55% physical damage reduction so I guess the initial damage is 6-6.5k per hit. 

From what I could find in wowhead comments (link above) 

By 55952 (8,235 – 3·14·62) on 2007/08/22 (Patch 2.1.3) |   |  
-- | -- | --

They don't hit hard, but cast a curse reducing Strength and movement speed by 70%. Decurse it if you can.   (Note:I dont know what curse is it referring to, maybe other npc)

27334 on 2008/01/23 (Patch 2.3.3)

I don't know what you consider "Hitting hard" but they're hitting me for 2000. (rogue btw)

To me it looks like that npc is overtuned and it causes a lot of trouble for groups, i think that npc over tune is the main cause of raids being unable to do the "ballroom" in Karazhan.

**Comment by MihawkEntropius** [comment]
[01:43:32]Selected: [Spectral Servant]
[01:43:32]SpawnId: 84992 Entry: 16407
