### ISSUE TITLE
[Quest] Plants of Zangarmash 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#586]
https://www.wowhead.com/npc=17909/lauranna-tharwell

After having delivered  https://www.wowhead.com/quest=9784/identify-plant-parts

She does not give me the repeatable quest  https://www.wowhead.com/quest=9802/plants-of-zangarmarsh

**Comment by Alucard-entropius** [comment]
Available until honored only.
https://www.wowhead.com/quest=9802/plants-of-zangarmarsh#comments
