### ISSUE TITLE
 Shimmerwing Moth

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#59]
Hi,

 

There are many mob spawns on Excalibur which make no sense, because when you pull that NPC it immediately evades and/or disappears.

Here's one of them. This one also says you're out of range when you're not.

It's in Eco-Dome Midrealm. 

https://www.youtube.com/watch?v=sRIsftooseo&feature=youtu.be

**Comment by Alucard-entropius** [comment]
![Wow_JWRvYc3o4V](https://user-images.githubusercontent.com/62255649/80802101-a199c100-8bae-11ea-80c4-9e9b28b1ae20.png)
appears as moth's spawn point is higher in the sky, as his corpse is upthere if you kill it

**Comment by Nextcalibur** [comment]
Fixed.
