### ISSUE TITLE
[NPC][Ability] Detection of Invisibility - BloodMaul Dire Wolf

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#590]
https://www.wowhead.com/npc=20058/bloodmaul-dire-wolf
![WoWScrnShot_080620_021458](https://user-images.githubusercontent.com/63980522/89476546-3fdb8b00-d78b-11ea-83e4-bb733870ec04.jpg)

I think this is a more general issue with how npc see stealth targets , not just these wolves. 

As you can see in the screen shot, I am next to it, its 5 level below me but considering he should have the agroo radius as if I was not in stealth I can get too close to it. 

Its worth noting I have stealth bonuses (though it should not matter).

1. I am a night elf, shadowmeld. 
2. 3 Points in talents for stealth
3. Boots that increase stealth level by 1

**Comment by MihawkEntropius** [comment]
tested working
