### ISSUE TITLE
[Mana Tomb] [NPC] Mob bug

### ISSUE THREAD

**Issue by Rasnia** [Nextcalibur/Bugtracker#595]
In mana Tomb, when we engaged the dungeon, we arrived to the 3rd hall where there is a patroling Etheral Crypt Raider that walks from one end to the middle - when that mob is killed, the mob respawns after 10 second, continually within the end of Mana Tomb.

**Comment by tonine-entro** [comment]
Added video link for confirmation - https://streamable.com/99lw3t
