### ISSUE TITLE
[Raid][Karazhan][NPC][Ability] - Netherspite- Red Beam - Heal

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#596]
https://wowwiki.fandom.com/wiki/Netherspite

Perseverance (red) - Tank beam
Replenishes full health every tick.

It does not replenish health to full health as it should. 

Edit:
Health is modified - the first application gives +31,000 maximum health, with additional stacks reducing maximum health by 1000 per stack.

**Comment by MihawkEntropius** [comment]
The beam replenish HP. Closing
