### ISSUE TITLE
Doctor Weavil

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#60]
I dont think this was fixed as it was scheduled in august for next revision.

https://classic.wowhead.com/npc=15552/doctor-weavil

Doctor Weavil seems to have the opposite problem as Nefarian recently had: Doc is friendly while he must be hostile (so players and kill him and get Dragonic for Dummies chapter I).

**Comment by Alucard-entropius** [comment]
![Wow_porrOklmUh](https://user-images.githubusercontent.com/62255649/80757473-812d2080-8b34-11ea-88a3-d0bf4af142ee.png)

**Comment by Nextcalibur** [comment]
Fixed.
