### ISSUE TITLE
Tzerak on Bloodmyst isle despawns on killing, rather than leaving a lootable corpse

### ISSUE THREAD

**Issue by kasamuel** [Nextcalibur/Bugtracker#600]
Tzerak should de-spawn after 2 minutes of standing still, but instead de-spawns after being killed. There is nothing for the player to loot, including the quest item he drops.

https://www.wowhead.com/npc=17528/tzerak

**Comment by tonine-entro** [comment]
Confirmed: NPC dies and instantly respawns at the summon point.

**Comment by MihawkEntropius** [comment]
lootable, working.
