### ISSUE TITLE
[NPC] Magram and Gelkis Centaur are hostile

### ISSUE THREAD

**Issue by SFCDaniel** [Nextcalibur/Bugtracker#603]
Magram and Gelkis Centaur in Desolace are neutral but attack on sight!
They should not attack, only if they are below unfriendly 

all npcs of the both Factions are affected

**Comment by Alucard-entropius** [comment]
You can untoggle "At War" with neutral faction in your Reputation tab.

**Comment by SFCDaniel** [comment]
i didn't have the 2 Factions unlocked at this time  (which is either done via killing a member of the faction or by accepting the Alliance quest for one side or the other)
Iirc they had no "At War" Status from the getgo when i played Classic Wow(retail).
