### ISSUE TITLE
[mechanic] Mental Agility does not affect Chastise

### ISSUE THREAD

**Issue by SFCDaniel** [Nextcalibur/Bugtracker#605]
The Mana Cost reduction from Discipline Priest Talent: Mental Agility
does not work with the Spell Chastise - its Mana costs are not reduced although its an instant cast

**Comment by Scalebeard** [comment]
While Chastise absolutely is an instant cast and priest spell, it appears to be a bit special due to being a Racial. We will require a source for this claim before being able to proceed with the report.

**Comment by SFCDaniel** [comment]
https://classic.wowhead.com/spell=14780/mental-agility
in classic it affected all instant Priest racials
it also affects https://wow.gamepedia.com/Symbol_of_Hope_(old) the other Draenei Racial here on the Server 
(13 Mana instead of 15)
