### ISSUE TITLE
Zuluhed the whacked spawns every time a quest is accepted, regardless of if players are in same group

### ISSUE THREAD

**Issue by kasamuel** [Nextcalibur/Bugtracker#606]
Zuluhead the whacked spawns every time a quest is accepted, regardless of if players are in same group.

2 zuluheads spawned on top of each other when 2 people in same group accepted quest. No prompt "x is starting this quest, would you like to too?" came up.
Neither zuluhead was able do be de-spawned by ranging, quest was completed by leashing one and ranging the other.
Possible there is still a zuluhead there.

**Comment by Scalebeard** [comment]
Confirmed. The group leader accepting the quest makes no difference for the rest of the part. They are all forced to accept the quest separately and spawn another Zuluhed NPC.

**Comment by MihawkEntropius** [comment]
tested fixed
