### ISSUE TITLE
High botanist Freywinn tranquility persists after flayers are dead

### ISSUE THREAD

**Issue by kasamuel** [Nextcalibur/Bugtracker#607]
High botanist Freywinn tranquility persists after flayers are dead, making him un-killable.
The tranquility should only persist for as long as the flayers are alive, but it persists for the full 45 sec duration, healing him out of normal killing range. Makes boss unkillable.

**Comment by MihawkEntropius** [comment]
To clarify, its related to adds spawning under the bridge and not being possible to kill them. 

It should be fine if you drag the boss to the other side of the bridge at pull. 

It does require a fix though.

**Comment by MihawkEntropius** [comment]
tested fixed
