### ISSUE TITLE
Warlock´s Demonic Sacrifice malfunction

### ISSUE THREAD

**Issue by Femlock** [Nextcalibur/Bugtracker#609]
When sacrificing (Demonic sacrifice) a voidwalker or a felguard a wrong buff is applied - it applies succubus sacrifice buff in both cases.

**Comment by Alucard-entropius** [comment]
[](https://i.imgur.com/aVC2fsb.png)
Demonic Sacrifice on Felguard works as intended

**Comment by Alucard-entropius** [comment]
[Picture](https://i.imgur.com/exCUmvx.png)
Demonic Sacrifice doesnt work as intended for Voidwalker

**Comment by MihawkEntropius** [comment]
tested and fixed
