### ISSUE TITLE
redundant Telredor elevator

### ISSUE THREAD

**Issue by SFCDaniel** [Nextcalibur/Bugtracker#612]
Telredor Refuge in Zangarmarsh has 3 of the Ground to upper level elevators
it should be only one.

1 is almost identical one further behind time wise

**Comment by MihawkEntropius** [comment]
I dont see anything wrong with the elevator in Telredor, please provide more data, perhaps record of what you think is a bug in game. 

On my client there's only one elevator platform that is moving.

**Comment by SFCDaniel** [comment]
Hmm atm its normal for me too, it must have been fixed in between.
was really several of them the last days and i didn't change anything on my client.

**Comment by tonine-entro** [comment]
Can only see 1 elevator. Could be a rendering issue. Try to reload ui if it happens again. Also, provide some screenshots or videos next time. Thanks.
