### ISSUE TITLE
[Quest][Blade's Edge Mountains] Fire at Will

### ISSUE THREAD

**Issue by StefanoElia** [Nextcalibur/Bugtracker#615]
The quest [Fire at Will](https://www.wowhead.com/quest=10911/fire-at-will) does not work.
After taking control of the cannons, pet bar with abilities does not show. 
So it's not possible to cast the spell to destroy the gates, nor cast the spell to kill imps.

**Comment by MihawkEntropius** [comment]
Hello, 

I have tested this quest and the pet bar is appearing.

Some solutions for your pet bar could be :
1. Disable add ons that modify your UI, especially bars, for example Bartender if you use it. 
2. If your pet bar is not shown you can press SHIFT+P to make it appear (unless this was changed by you in key bind settings, SHIFT+P is default)
3. perhaps your pet, pet bar, is bugging it for you? if you use a pet. 

I will close this report for now, if this issue persist for you, contact me or other staff members on Discord, cheers!

-Regards.
