### ISSUE TITLE
Thrall in OHF, quest delivery

### ISSUE THREAD

**Issue by Alucard-entropius** [Nextcalibur/Bugtracker#616]
In case of wipe and/or Thrall's death, players who didnt turn in quest before, cannot do it upon respawn of Thrall.
More information from Carebot.

**Comment by carebot90** [comment]
Yes, what happened is that thrall was started too early in a rushed way. 

Some players didnt deliver it in time, we let thrall die to reset. 

After respawn it was impossible for players to deliver the bombs quest and take next quest to escort thrall.

**Comment by MihawkEntropius** [comment]
Tested working
