### ISSUE TITLE
[NPC][Mechanic] Selin Fireheart - Crystal Mana Draining

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#625]
During the fight with Selin he start channeling crystals in the room which refills his mana. 

https://www.wowhead.com/npc=24723/selin-fireheart#comments;mode:heroic
At some point, he will siphon a crystal and gain 10% mana per tick until you destroy the crystal.
When he's been interupted or done channeling he'll start using his mana for AE that will hit your party for about 1000 damage per tick.

Right now he does the channeling animation but his mana is not being refilled.

**Comment by MihawkEntropius** [comment]
Tested working.
