### ISSUE TITLE
[Quest][Blade's Edge Mountains] Guardian of the Monument

### ISSUE THREAD

**Issue by Indanos** [Nextcalibur/Bugtracker#628]
Apologies if this is something already reported, I couldn't find another open Ogri'la issue.

A group of us attempted this quest earlier this evening and completed the sequencing successfully twice. As a refresher this quest is a group version of the solo daily quest 'The Relic's Emanation' in which the player has to complete a series of 'Simon Says'-style sequences. This group quest is supposed to culminate in an elite mob (Apexis Guardian) spawning, but on both our successful attempts of the sequences, the monument behaved as though we failed and no spawn. I don't have any videos or screenies at the moment but if necessary I can try to gather some later on.

**Comment by MihawkEntropius** [comment]
It should be summonable at https://www.wowhead.com/object=185944/apexis-monument
The quest for it is https://www.wowhead.com/quest=11059/guardian-of-the-monument#comments
The npc : https://www.wowhead.com/npc=22275/apexis-guardian#comments

**Comment by MihawkEntropius** [comment]
https://ibb.co/CBMWqC6

Worked for me.

**Comment by Azelen** [comment]
The mob is summoned as "punishment" for unsuccessful attempt. So you actually have to fail to summon him. Works as intended.

https://www.wowhead.com/quest=11059/guardian-of-the-monument#comments
