### ISSUE TITLE
SSC - Trash immunity

### ISSUE THREAD

**Issue by Jamesrandi** [Nextcalibur/Bugtracker#630]
**Coilfang Priestress** immune to polymorph

https://wowwiki-archive.fandom.com/wiki/Coilfang_Priestess

"Can be polymorphed, sapped, seduced or mind-controlled and feared. "

**Greyheart Nether-Mage** immune to polymorph & fear

https://wowwiki-archive.fandom.com/wiki/Greyheart_Nether-Mage

"They are vulnerable to sheeping and fear."

**Greyheart Tidecaller** immune to polymorph & fear

https://wowwiki-archive.fandom.com/wiki/Greyheart_Tidecaller

"These are vulnerable to polymorph and fear."

**Greyheart Skulker** immune to fear & polymorph

https://wowwiki-archive.fandom.com/wiki/Greyheart_Skulker

"Sheepable Fearable"

**Greyheart Shieldbearer** immune to polymorph, sap & fear

https://wowwiki-archive.fandom.com/wiki/Greyheart_Shield-Bearer

"Susceptible to Polymorph.
Can be sapped
Can be feared"

**Comment by MihawkEntropius** [comment]
Selected: [Coilfang Priestess]
SpawnId: 93815 Entry: 21220
Mechanic Immunity: Charm, Disorient, Disarm, Distract, Fear, Root, Silence, Sleep, Snare, Stun, Freeze, Incapacitate, Polymorph, Banish, Horror, Interrupt Cast, Daze, Sap.
