### ISSUE TITLE
SSC - Leotheras the Blind

### ISSUE THREAD

**Issue by Jamesrandi** [Nextcalibur/Bugtracker#632]
Leotheras movementspeed in Whirlwind is waaaay too fast
There is no way to avoid getting hit right now as he is just whirling with 4x sprintspeed through the room.
As Wow-wiki states:
"If that person runs away fast and far enough, he will deaggro and whirl towards someone else. It is possible to have ALL raid members avoid being hit."
So Whirlwind speed should be slightly faster than player run speed so you can avoid getting hit by strategically spreading and running away from him.

https://wowwiki-archive.fandom.com/wiki/Leotheras_the_Blind

**Comment by Azelen** [comment]
His run speed is 214% of player's base run speed. This value is confirmed by data gathered on retail. There's no speed change detected during Whirlwind.

Also checked this video from retail and speed seems to be approximately the same. https://www.youtube.com/watch?v=8SWVNk-KfUI

**Comment by Jamesrandi** [comment]
Youtube video from Method is sped up by around 20% (check 0:30 and 8:30 and compare with chat timestamps 22:09 & 22:19)
You can see player movement speed is off too.

Leo is still slower on that vid (even with sped up) from retail than what we saw live on the server.

**Comment by Azelen** [comment]
https://www.youtube.com/watch?v=IxbgetzFcU8 in this video also can see that he moves much faster than players during Whirllwind. Every second he randomly changes aggro during Whirlwind, you should try spreading out around the room like in this video, then he'll spend most of his time moving between random targets and you won't receive much damage from Whirlwind itself.

**Comment by Jamesrandi** [comment]
couldn't recreate his movement speed on 21.03.2021

might have been a bug
