### ISSUE TITLE
[Thori'dal][Attackspeed stacking with quiver] [Item]

### ISSUE THREAD

**Issue by spacecrazy** [Nextcalibur/Bugtracker#636]
As title states the Thori'dal legendary 's bow has the effect for an attack speed buff which does not stack with quivers. Currently the speed buff stacks with quivers own attack speed buff.

**Comment by Alucard-entropius** [comment]
![image](https://user-images.githubusercontent.com/62255649/111963053-628c9b00-8af3-11eb-89a3-42392b2e66ff.png)
Its not actually gamebreaking or anything, i tested it with naked lvl 70 hunter
It's not stacking with quiver or ammo pouch but it will penalise you if you equip and then unequip quiver, taking away 15% haste. it is a bug but Not a priority to fix.
(who uses quiver with thoridal anyway?)

**Comment by MihawkEntropius** [comment]
tested and fixed
