### ISSUE TITLE
Quest   All quests at level 70

### ISSUE THREAD

**Issue by Peachtre** [Nextcalibur/Bugtracker#639]
All quests,  dailys included do not pay the gold as level 70 should get.  All dailys are 1/3 the gold of retail.  One of the rewards for getting to 70 is doing the quests to get gold.  should get 30-40 gold for some quests,  heroic daily should be 46 gold,  each quest at 70 should be minimum 20 gold and dailys 23-24 gold or more for some of those. Its not doing quests at 70 for the current gold

**Comment by MihawkEntropius** [comment]
I took https://tbcdb.com/?quest=11536 "don't stop now" an isle daily as a test subject, xp reward is 12650

at 69 the gold reward is 4g 40silver
at 70 the gold reward is 11g 99Silver
Difference is 7.59gold
 
https://wowpedia.fandom.com/wiki/Experience_point#Money_for_experience_at_top_level
Money in copper = XP * 6 (Level 1-80 quests)

That would mean at 12650 xp  , 12650 x 6 = 75900 , converted into gold that is 7.59 gold 

This shows that the reward from quests at 70 is correct.

Is this a bug is discussable depending on what the ratio of experience is considered at 70, as far as blizzlike goes, this would be blizzlike. 

If we want to have experience converted into gold at x2 rates then the gold reward for this specific quest would be 19,50gold.

**Comment by Peachtre** [comment]
Hmm I'll need to go into a lot more detail. The quests on live and on excal paid more as a max level toon, it's the same in all expansions of wow. I tested this with my shadow priest and lock on quests in 3 areas. The heroic daily for dungeons, the payout is a lot lower should be around 46 gold payout at level 70,  the  daily s on the island,  I tested 3 of the quests there, each paid 9 gold, getting the mana remnants from those creatures and killing those 5 robots ans using the thing on them.  This should be 18 gold plus for those, I didn't get a chance to test the rest but with all the dailys on the island we should expect about 230 gold. I did one of the horde quests in terrokar forest,  payout was 9 gold. I was deliberately grinding quests,  I did this on warmane outland, I did this on retail many times and I did on excal,  the figures for the quest payouts here are not the same. Either that's intended or that is a bug. It's mainly to compensate players at higher level and aimed at providing the gold for the epic flyer. It's actually a pretty big issue if its i tented as this is where most players get their gold for raiding and dungeons. To me it looks like there is no additional benifit to questing at may level.

**Comment by Peachtre** [comment]
I réread your coment and I see what you are saying,  I guess what I am saying is if the experience levels were the same, then this servers experience rates don't match what was on excal and tbc retail for years.  If your saying that the payout is correct, I'm saying the payouts don't match excal, and do t match the retail. I think this needs to be looked at.more granular and.compare. I am a quest completer and I like grinding quests when not farming for mats. The payouts for quests on this server don't match Blizs payout system or excal

**Comment by Peachtre** [comment]
The x2 rate matches retail and excal, this is what quests at 70 should payout. I guess that's why very few are not questing at the moment. Ifthe quests now pay out less then that's intended and they don't want it to match this.

**Comment by MihawkEntropius** [comment]
After talking with the Dev, it seems that the reward is lower because gold rates are x1 and on Exca it was x2. 

This is not a bug, unless gold rates are raised from x1 the gold rewarded from quests is blizzlike.
