### ISSUE TITLE
[Quest][Shadowmoon]The Booterang: A Cure For The Common Worthless Peon

### ISSUE THREAD

**Issue by Exithus** [Nextcalibur/Bugtracker#640]
https://tbcdb.com/?quest=11055
Throwing a booterang at lazy peons doesnt send them back to work or doesnt changes their status in any way, so you can just use booterang on sinle peon 20 times to get the quest complete

**Comment by MihawkEntropius** [comment]
Confirmed, thank you for the report

Quest item (used): 32680

Example of NPC:
[Disobedient Dragonmaw Peon]
SpawnId: 52266 Entry: 23311

**Comment by MihawkEntropius** [comment]
Tested and working.
