### ISSUE TITLE
[DUNGEON] Vazruden doesnt use all abilities.

### ISSUE THREAD

**Issue by Alucard-entropius** [Nextcalibur/Bugtracker#641]
On Heroic difficulty Vazruden should Shield Slam and Revenge
![image](https://user-images.githubusercontent.com/62255649/112720168-02379800-8efd-11eb-9be7-642aeb706e63.png)
[Source](https://wowpedia.fandom.com/wiki/Vazruden)

**Comment by Azelen** [comment]
Revenge will be fixed in the next update. But Shield Slam I can't confirm he actually knows this ability, it doesn't appear in wowhead snapshots from 2008.

**Comment by MihawkEntropius** [comment]
Tested, receiving revenge attacks.
