### ISSUE TITLE
Hunter Pets losing buffs on dismiss

### ISSUE THREAD

**Issue by Hannsre** [Nextcalibur/Bugtracker#644]
Not sure if it's really a bug or supposed to be that way. 
Dismissed my pet in ZA earlier so it doesn't pull, buffed it shortly before with Scroll of Agi and Str. Both were gone, also group buffs like Stam and MOTW. not sure tho if it lost it earlier when it died. 

I know it's not like that on Retail Classic, but can't remember from original TBC. 

Thx :)

**Comment by tonine-entro** [comment]
Hi @Azelen 
Seems the bug isn't fixed. 
Before dismiss pet has buffs like [Mend Pet], [Power Word: Fortitude]
![image](https://user-images.githubusercontent.com/67378152/116259954-e6414380-a793-11eb-8bcb-017ecad8b644.png)

After [Call Pet], it doesn't have any buff

![image](https://user-images.githubusercontent.com/67378152/116260061-feb15e00-a793-11eb-9473-a2feff280764.png)

**Comment by MihawkEntropius** [comment]
Tested & Working properly
