### ISSUE TITLE
[NPC] [SSC] Leotheras the Blind tauntable

### ISSUE THREAD

**Issue by DivineKofa** [Nextcalibur/Bugtracker#655]
Last night I joined a SSC pug where I had to tank, it occured to me that Leotheras is tauntable while he should be immune to taunts. It makes no sense, since it obsoletes the main boss mechanic, that dps and heals should stop any threat generation after every Whirlwind and on phase transitions so tanks could pick the boss.

Also source:
_"Like most raid bosses, Leotheras is immune to taunt."_
https://wowwiki-archive.fandom.com/wiki/Leotheras_the_Blind?oldid=1580841

**Comment by Azelen** [comment]
Only true for when he is in demon form.

**Comment by MihawkEntropius** [comment]
Currently its not possible to "taunt" either version/phase of this boss.
