### ISSUE TITLE
[NPC][Hellfire Peninsula] Netherhound missing Manaburn

### ISSUE THREAD

**Issue by Nefarianist** [Nextcalibur/Bugtracker#664]
Hi,

The Netherhound pet of the Fel Handler should have Manaburn but i never saw them casting/using it.

https://tbc.wowhead.com/npc=16950/netherhound#abilities

Tyvm

**Comment by MihawkEntropius** [comment]
[https://ibb.co/ZB0Q0Rt](url)

Working as intended
