### ISSUE TITLE
[transmogrification]

### ISSUE THREAD

**Issue by Quad27** [Nextcalibur/Bugtracker#666]
Hello,

I've noticed that if i transmog a set piece of my gear, the set bonus disappeares.
I have 4/8 pieces on my shaman, but when i use the transmog feature on my chest, the set bonus disappears, it says 3/8.

I've attached some pictures with before and after the process.

Can you please check it out?

Thank you,

Quad
![WoWScrnShot_071621_150134](https://user-images.githubusercontent.com/75359855/125945058-78e0fa84-77fe-4ff6-a72d-32b1efd2d425.jpg)
![WoWScrnShot_071621_150142](https://user-images.githubusercontent.com/75359855/125945062-3a6fea4a-f4f7-4322-9a06-136358111c3d.jpg)
![WoWScrnShot_071621_150148](https://user-images.githubusercontent.com/75359855/125945065-bbeb4722-b419-4dad-917a-b4efeaa427f6.jpg)

**Comment by Nextcalibur** [comment]
purely visual bug due to limitation in client. stats and bonuses still apply on the server side.
