### ISSUE TITLE
[Item][Engineering][Raid][Karazhan] Schematic drop rate from Attumen the Huntsman

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#670]
The drop rate for https://tbc.wowhead.com/item=23809/schematic-stabilized-eternium-scope is currently at 1% (checked with GM command). 

The drop should be 8% , reference : https://tbc.wowhead.com/npc=16152/attumen-the-huntsman

**Comment by Azelen** [comment]
Fixed
