### ISSUE TITLE
[Item][Enchanting][Formula] - Formula: Enchant Cloak - Steelweave

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#671]
https://tbc.wowhead.com/item=35756/formula-enchant-cloak-steelweave 

Should drop at a rate of 11% as reported by tbc.wowhead 

Actual drop rate currently is 1% , tested with Debug Loot command. 

Selected: [Priestess Delrissa]
SpawnId: 96966 Entry: 24560

**Comment by Azelen** [comment]
Fixed
