### ISSUE TITLE
[Item][Enchanting][Formula] - Formula: Enchant 2H Weapon - Savagery

### ISSUE THREAD

**Issue by MihawkEntropius** [Nextcalibur/Bugtracker#672]
https://tbc.wowhead.com/item=22554/formula-enchant-2h-weapon-savagery

Should drop at a rate of 7% in normal and 15% in heroic and 7% in normal, currently the drop rate is 1%

Selected: [Shattered Hand Centurion]
SpawnId: 62923 Entry: 17465

**Comment by Azelen** [comment]
Fixed
