### ISSUE TITLE
Disarming armed NPC's doesn't reduce their damage

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#80]
While it should.

 

So I guess you're using only mobs strength as a randomized damage variable and not considering their weapons at all.

It's gonna be a lot of work to do so for all mobs, but ye... it works this way at Blizzard servers. Atm rogues Riposte effect or warriors disarm is pretty much useless on armed NPC's.

Azelen Reply:  

Out database is missing some required information that must be added for every creature in world before this can be fixed.

**Comment by MihawkEntropius** [comment]
Tested on Prince Phase 2, damage is significantly reduced, closing.
