### ISSUE TITLE
 Caster NPC's not coming to melee after being interrupted 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#82]
For example these NPCs: [Bloodsail Warlock] - when they cast a spell and you interrupt them, they stay there in front of you and they don't attack with melee, as they do on retail WoW. They only start casting spells again, when the effect of counterspell/silence ends. They do melee though when their mana is depleted.

It's easier for players to handle them like this but still it's not how it's supposed to be.

**Comment by Alucard-entropius** [comment]
Works. Fixed
