### ISSUE TITLE
Pit Commander

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#89]
https://www.wowhead.com/npc=18945/pit-commander

Pit Commander this elite missing some abilities like Cleave ,Rain of Fire and Summon Infernals

9zkg_wowscrnshot_062116_130347.jpg

**Comment by Alucard-entropius** [comment]
![Wow_xgAOr86ImF](https://user-images.githubusercontent.com/62255649/80725149-f97aee00-8b02-11ea-97b1-bbe2ef9d20b1.png)

**Comment by Nextcalibur** [comment]
Duplicate. Already fixed.
