### ISSUE TITLE
Silithid Swarmer

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#90]
Quest: Noxious Lair Investigation

Npc: Centipaar Swarmer

Area: Tanaris (West) 

Bug: The NPC called "Centipaar Swarmer" summons bugs which hp varies from 2-1500 ish, the spawn cd is really fast so they will swarm in mere moments. We tested this mechanic on one "Centipaar Swarmer" and he easily summoned 20 ish swarmers. Basically this method can be used as griefing etc since the bugs wont actually have any return point, so they will follow you all the way to orgrimmar if you want. Also its very annoying for the people who are doing the quest since they can technically only kill the other npc included in the quest. (Centipaar Stinger & Centipaar Worker)

 

Attachments below

(Shows that there are tons of bugs!)

[attachment=12845:WoWScrnShot_091416_044848.jpg]

 

(Shows that those bugs have unlimited range)

[attachment=12846:WoWScrnShot_091416_044635.jpg]

 

Imgur link for better quality pictures: http://imgur.com/a/oWao9

**Comment by Alucard-entropius** [comment]
Adds all have 2hp and despawn after killing Centipaar Swarmer. Fixed
