### ISSUE TITLE
Felguard Destroyer 

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#96]
Those NPCs missing their abilities.

 

They should:

 

http://db.excalibur-wow.com/?npc=18977#controlled-abilities

 

Location: Between "Legion Hold" and "The Dark Portal"

**Comment by Alucard-entropius** [comment]
![Wow_t203redTym](https://user-images.githubusercontent.com/62255649/80705668-1acde100-8ae7-11ea-92c8-0669aea6215e.png)
It has all 3 abilities it should have.
