### ISSUE TITLE
Scout Navrin

### ISSUE THREAD

**Issue by carebot90** [Nextcalibur/Bugtracker#98]
Scout Navrin (https://www.wowhead.com/npc=22364/scout-navrin) Is always under the texture, it needs to be pulled up so players can accept/hand in quests from him, can he be moved?

 

See video below: https://youtu.be/a8A_I-1KEE0

**Comment by Alucard-entropius** [comment]
![Wow_Ap40m1oUKp](https://user-images.githubusercontent.com/62255649/80640859-507db600-8a64-11ea-9c4b-b3459a953e97.png)
Fixed.
